const clinicQuery = {
  createClinicTable: `
  CREATE TABLE IF NOT EXISTS clinic (
  clinic_id int(11) NOT NULL AUTO_INCREMENT,
  tenant_id int(11) NOT NULL,
  clinic_name varchar(50) NOT NULL,
  email varchar(255) DEFAULT NULL,
  phone_number varchar(15) NOT NULL,
  alternate_phone_number varchar(15) DEFAULT NULL,
  branch varchar(50) DEFAULT NULL,
  website varchar(255) DEFAULT NULL,
  address text NOT NULL,
  city varchar(100) NOT NULL,
  state varchar(100) NOT NULL,
  country varchar(50) NOT NULL,
  pin_code varchar(6) NOT NULL,
  license_number varchar(10) NOT NULL,
  gst_number varchar(15) DEFAULT NULL,
  pan_number varchar(10) DEFAULT NULL,
  established_year int(4) NOT NULL,
  total_doctors int(3) DEFAULT NULL,
  total_patients int(11) DEFAULT NULL,
  total_dental_chairs int(4) DEFAULT NULL,
  number_of_assistants int(4) DEFAULT NULL,
  available_services longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(available_services)),
  operating_hours longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(operating_hours)),
  insurance_supported tinyint(1) NOT NULL DEFAULT 0,
  ratings decimal(3,2) DEFAULT NULL,
  reviews_count int(11) DEFAULT NULL,
  emergency_support tinyint(1) NOT NULL DEFAULT 0,
  teleconsultation_supported tinyint(1) NOT NULL DEFAULT 0,
  clinic_logo varchar(255) DEFAULT NULL,
  parking_availability tinyint(1) NOT NULL DEFAULT 0,
  pharmacy tinyint(1) DEFAULT NULL,
  wifi tinyint(1) NOT NULL DEFAULT 0,
  created_by varchar(30) NOT NULL DEFAULT 'ADMIN',
  created_time timestamp NOT NULL DEFAULT current_timestamp(),
  updated_by varchar(30) DEFAULT NULL,
  updated_time timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (clinic_id),
  KEY fk_tenant (tenant_id),
  KEY idx_phone_number (phone_number),
  CONSTRAINT fk_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`

,
  addClinic: `INSERT INTO clinic (
      tenant_id,
    clinic_name,
    email,
    phone_number,
    alternate_phone_number,
    branch,
    website,
    address,
    city,
    state,
    country,
    pin_code,
    license_number,
    gst_number,
    pan_number,
    established_year,
    total_doctors,
    total_patients,
    total_dental_chairs,
    number_of_assistants,
    available_services,
    operating_hours,
    insurance_supported,
    ratings,
    reviews_count,
    emergency_support,
    teleconsultation_supported,
    clinic_logo,
    parking_availability,
    pharmacy,
    wifi,
    created_by
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);`,
  getAllClinicByTenantId: `select clinic_id,
    tenant_id,
    clinic_name,
    email,
    phone_number,
    alternate_phone_number,
    branch,
    website,
    address,
    city,
    state,
    country,
    pin_code,
    license_number,
    gst_number,
    pan_number,
    established_year,
    total_doctors,
    total_patients,
    total_dental_chairs,
    number_of_assistants,
    available_services,
    operating_hours,
    insurance_supported,
    ratings,
    reviews_count,
    emergency_support,
    teleconsultation_supported,
    clinic_logo,
    parking_availability,
    pharmacy,
    wifi,
    created_by,
    created_time,
    updated_by,
    updated_time
FROM clinic
WHERE tenant_id = ? limit ? offset ?,
  getClinicByTenantIdAndClinicId: select * from clinic where tenant_id=? and clinic_id=?`,
  checkClinicExistsByTenantIdAndClinicId: `select 1 from clinic where tenant_id=? and clinic_id=?`,
  updateClinic: `UPDATE clinic SET 
  tenant_id=?,
    clinic_name = ?,
    email = ?,
    phone_number = ?,
    alternate_phone_number = ?,
    branch = ?,
    website = ?,
    address = ?,
    city = ?,
    state = ?,
    country = ?,
    pin_code = ?,
    license_number = ?,
    gst_number = ?,
    pan_number = ?,
    established_year = ?,
    total_doctors = ?,
    total_patients = ?,
    total_dental_chairs = ?,
    number_of_assistants = ?,
    available_services = ?,
    operating_hours = ?,
    insurance_supported = ?,
    ratings = ?,
    reviews_count = ?,
    emergency_support = ?,
    teleconsultation_supported = ?,
    clinic_logo = ?,
    parking_availability = ?,
    pharmacy = ?,
    wifi = ?,
    updated_by = ?,
    updated_time = CURRENT_TIMESTAMP
WHERE tenant_id=? and clinic_id = ?,
  deleteClinicByTenantIdAndClinicId: delete from clinic where tenant_id=? and clinic_id=?`,
};

module.exports = { clinicQuery };
