const createTableQuery = {
  addAppointment: `CREATE TABLE IF NOT EXISTS appointment (
  appointment_id int(11) NOT NULL AUTO_INCREMENT,
  tenant_id int(6) NOT NULL,
  patient_id int(11) NOT NULL,
  dentist_id int(11) NOT NULL,
  clinic_id int(11) NOT NULL,
  appointment_date date NOT NULL,
  start_time time NOT NULL,
  end_time time NOT NULL,
  status enum('SC','CP','CL') NOT NULL DEFAULT 'SC',
  appointment_type enum('IP','TC') NOT NULL DEFAULT 'TC',
  consultation_fee decimal(10,2) DEFAULT NULL,
  discount_applied decimal(10,2) NOT NULL DEFAULT 0.00,
  payment_status enum('P','UP','PD') NOT NULL DEFAULT 'P',
  payment_method enum('CH','CD','IN','O') NOT NULL,
  visit_reason text DEFAULT NULL,
  follow_up_needed tinyint(1) NOT NULL DEFAULT 0,
  reminder_method enum('SMS','EM','CL','WA') NOT NULL DEFAULT 'SMS',
  notes text DEFAULT NULL,
  created_by varchar(20) NOT NULL,
  created_time timestamp NOT NULL DEFAULT current_timestamp(),
  updated_by varchar(20) DEFAULT NULL,
  updated_time timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (appointment_id),
  KEY fk_appointment_tenant (tenant_id),
  KEY fk_appointment_patient (patient_id),
  KEY fk_appointment_dentist (dentist_id),
  KEY fk_appointment_clinic (clinic_id),
  CONSTRAINT fk_appointment_clinic FOREIGN KEY (clinic_id) REFERENCES clinic (clinic_id) ON UPDATE CASCADE,
  CONSTRAINT fk_appointment_dentist FOREIGN KEY (dentist_id) REFERENCES dentist (dentist_id) ON UPDATE CASCADE,
  CONSTRAINT fk_appointment_patient FOREIGN KEY (patient_id) REFERENCES patient (patient_id) ON UPDATE CASCADE,
  CONSTRAINT fk_appointment_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;`,
  addAsset: `
 CREATE TABLE IF NOT EXISTS asset (
  asset_id int(11) NOT NULL AUTO_INCREMENT,
  tenant_id int(6) NOT NULL,
  clinic_id int(11) NOT NULL,
  asset_name varchar(100) NOT NULL,
  asset_status varchar(50) DEFAULT NULL,
  asset_type varchar(50) DEFAULT NULL,
  asset_photo varchar(255) DEFAULT NULL,
  quantity int(4) DEFAULT NULL,
  price decimal(10,2) DEFAULT NULL,
  allocated_to varchar(100) DEFAULT NULL,
  purchased_date date DEFAULT NULL,
  purchased_by varchar(50) NOT NULL,
  expired_date date DEFAULT NULL,
  invoice_number int(3) DEFAULT NULL,
  description text DEFAULT NULL,
  created_by varchar(30) NOT NULL DEFAULT 'ADMIN',
  created_time datetime NOT NULL DEFAULT current_timestamp(),
  updated_by varchar(30) DEFAULT NULL,
  updated_time datetime DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (asset_id)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;`,
  addClinic: `CREATE TABLE IF NOT EXISTS clinic (
  clinic_id int(11) NOT NULL AUTO_INCREMENT,
  tenant_id int(6) NOT NULL,
  clinic_name varchar(100) NOT NULL,
  email varchar(255) DEFAULT NULL,
  phone_number varchar(15) NOT NULL,
  alternate_phone_number varchar(15) DEFAULT NULL,
  branch varchar(50) DEFAULT NULL,
  website varchar(255) DEFAULT NULL,
  address text NOT NULL,
  city varchar(100) NOT NULL,
  state varchar(100) NOT NULL,
  country varchar(50) NOT NULL,
  pin_code varchar(6) NOT NULL,
  license_number varchar(10) NOT NULL,
  gst_number varchar(15) DEFAULT NULL,
  pan_number varchar(10) DEFAULT NULL,
  established_year int(4) NOT NULL,
  total_doctors int(3) DEFAULT NULL,
  total_patients int(11) DEFAULT NULL,
  total_dental_chairs int(4) DEFAULT NULL,
  number_of_assistants int(4) DEFAULT NULL,
  available_services longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(available_services)),
  operating_hours longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(operating_hours)),
  insurance_supported tinyint(1) NOT NULL DEFAULT 0,
  ratings decimal(3,2) DEFAULT NULL,
  reviews_count int(11) DEFAULT NULL,
  emergency_support tinyint(1) NOT NULL DEFAULT 0,
  teleconsultation_supported tinyint(1) NOT NULL DEFAULT 0,
  clinic_logo varchar(255) DEFAULT NULL,
  parking_availability tinyint(1) NOT NULL DEFAULT 0,
  pharmacy tinyint(1) DEFAULT NULL,
  wifi tinyint(1) NOT NULL DEFAULT 0,
  created_by varchar(30) NOT NULL DEFAULT 'ADMIN',
  created_time timestamp NOT NULL DEFAULT current_timestamp(),
  updated_by varchar(30) DEFAULT NULL,
  updated_time timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (clinic_id),
  KEY fk_tenant (tenant_id),
  KEY idx_phone_number (phone_number),
  CONSTRAINT fk_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
  addDentist: `CREATE TABLE IF NOT EXISTS dentist (
  dentist_id int(11) NOT NULL AUTO_INCREMENT,
  tenant_id int(6) NOT NULL,
  clinic_id int(11) DEFAULT NULL,
  first_name varchar(50) NOT NULL,
  last_name varchar(50) NOT NULL,
  gender enum('M','F','TG') DEFAULT 'M',
  date_of_birth date DEFAULT NULL,
  email varchar(255) DEFAULT NULL,
  phone_number varchar(15) NOT NULL,
  alternate_phone_number varchar(15) DEFAULT NULL,
  specialization longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(specialization)),
  qualifications longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(qualifications)),
  member_of longtext DEFAULT NULL,
  experience_years int(2) NOT NULL,
  license_number varchar(20) NOT NULL,
  clinic_name varchar(150) DEFAULT NULL,
  clinic_address varchar(300) DEFAULT NULL,
  city varchar(100) NOT NULL,
  state varchar(100) NOT NULL,
  country varchar(50) NOT NULL,
  pin_code varchar(6) NOT NULL,
  working_hours longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(working_hours)),
  available_days longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(available_days)),
  consultation_fee decimal(10,2) DEFAULT NULL,
  ratings decimal(3,2) DEFAULT NULL,
  reviews_count int(11) DEFAULT NULL,
  appointment_count int(11) DEFAULT NULL,
  profile_picture varchar(255) DEFAULT NULL,
  bio longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(bio)),
  teleconsultation_supported tinyint(1) NOT NULL DEFAULT 0,
  insurance_supported tinyint(1) NOT NULL DEFAULT 0,
  languages_spoken longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(languages_spoken)),
  awards_certifications longtext DEFAULT NULL,
  social_links longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(social_links)),
  last_login timestamp NULL DEFAULT NULL,
  duration text DEFAULT NULL,
  created_by varchar(30) NOT NULL,
  created_time timestamp NOT NULL DEFAULT current_timestamp(),
  updated_by varchar(30) DEFAULT NULL,
  updated_time timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (dentist_id),
  KEY idx_tenant_id (tenant_id),
  KEY idx_phone_number (phone_number),
  KEY clinic_id (clinic_id),
  CONSTRAINT fk_dentist_clinic FOREIGN KEY (clinic_id) REFERENCES clinic (clinic_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_dentist_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,

  addPatient: `CREATE TABLE IF NOT EXISTS patient (
  patient_id int(11) NOT NULL AUTO_INCREMENT,
  tenant_id int(6) NOT NULL,
  first_name varchar(50) NOT NULL,
  last_name varchar(50) NOT NULL,
  email varchar(255) DEFAULT NULL,
  phone_number varchar(15) NOT NULL,
  alternate_phone_number varchar(15) DEFAULT NULL,
  date_of_birth date NOT NULL,
  gender enum('M','F','TG') NOT NULL DEFAULT 'M',
  blood_group varchar(10) DEFAULT NULL,
  address text NOT NULL,
  city varchar(100) NOT NULL,
  state varchar(100) NOT NULL,
  country varchar(50) NOT NULL,
  pin_code varchar(6) NOT NULL,
  pre_history text DEFAULT NULL,
  current_medications text DEFAULT NULL,
  dentist_preference int(11) DEFAULT NULL,
  smoking_status enum('N','F','C') NOT NULL DEFAULT 'N',
  alcohol_consumption enum('N','OC','R') NOT NULL,
  emergency_contact_name varchar(255) NOT NULL,
  emergency_contact_phone varchar(15) NOT NULL,
  insurance_provider varchar(255) DEFAULT NULL,
  insurance_policy_number varchar(10) DEFAULT NULL,
  treatment_history longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(treatment_history)),
  appointment_count int(11) DEFAULT NULL,
  last_appointment_date timestamp NULL DEFAULT NULL,
  profile_picture varchar(255) DEFAULT NULL,
  created_by varchar(30) NOT NULL,
  created_time timestamp NOT NULL DEFAULT current_timestamp(),
  updated_by varchar(30) DEFAULT NULL,
  updated_time timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  first_visit_date timestamp NULL DEFAULT NULL,
  referred_by varchar(100) DEFAULT NULL,
  profession varchar(100) DEFAULT NULL,
  tooth_details text DEFAULT NULL,
  PRIMARY KEY (patient_id),
  KEY fk_patient_tenant (tenant_id),
  KEY fk_patient_dentist (dentist_preference),
  CONSTRAINT fk_patient_dentist FOREIGN KEY (dentist_preference) REFERENCES dentist (dentist_id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_patient_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;`,

  addPrescription: `CREATE TABLE IF NOT EXISTS prescription (
  prescription_id int(11) NOT NULL AUTO_INCREMENT,
  tenant_id int(6) NOT NULL,
  clinic_id int(11) NOT NULL,
  patient_id int(11) NOT NULL,
  dentist_id int(11) NOT NULL,
  treatment_id int(11) NOT NULL,
  medication text DEFAULT NULL,
  generic_name varchar(255) DEFAULT NULL,
  brand_name varchar(255) DEFAULT NULL,
  dosage text DEFAULT NULL,
  frequency varchar(50) DEFAULT NULL,
  quantity int(11) DEFAULT NULL,
  refill_allowed tinyint(1) DEFAULT 0,
  refill_count int(11) DEFAULT 0,
  side_effects text DEFAULT NULL,
  start_date date DEFAULT NULL,
  end_date date DEFAULT NULL,
  instructions text DEFAULT NULL,
  notes text DEFAULT NULL,
  is_active tinyint(1) NOT NULL DEFAULT 1,
  created_by varchar(30) NOT NULL,
  created_time timestamp NOT NULL DEFAULT current_timestamp(),
  updated_by varchar(30) DEFAULT NULL,
  updated_time timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (prescription_id),
  KEY fk_prescription_patient (patient_id),
  KEY fk_prescription_dentist (dentist_id),
  KEY fk_prescription_treatment (treatment_id),
  KEY fk_prescription_tenant (tenant_id),
  KEY fk_prescription_clinic (clinic_id),
  CONSTRAINT fk_prescription_clinic FOREIGN KEY (clinic_id) REFERENCES clinic (clinic_id) ON UPDATE CASCADE,
  CONSTRAINT fk_prescription_dentist FOREIGN KEY (dentist_id) REFERENCES dentist (dentist_id) ON UPDATE CASCADE,
  CONSTRAINT fk_prescription_patient FOREIGN KEY (patient_id) REFERENCES patient (patient_id) ON UPDATE CASCADE,
  CONSTRAINT fk_prescription_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_prescription_treatment FOREIGN KEY (treatment_id) REFERENCES treatment (treatment_id) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;`,

  addStatusType: `
 CREATE TABLE IF NOT EXISTS statustype (
  status_type_id int(11) NOT NULL AUTO_INCREMENT,
  status_type varchar(100) NOT NULL,
  created_by varchar(30) NOT NULL,
  created_time datetime NOT NULL DEFAULT current_timestamp(),
  updated_by varchar(30) DEFAULT NULL,
  updated_time datetime DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (status_type_id),
  UNIQUE KEY status_type (status_type)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

`,
  addStatusTypeSub: `
CREATE TABLE IF NOT EXISTS statustypesub (
  status_type_sub_id int(11) NOT NULL AUTO_INCREMENT,
  tenant_id int(6) NOT NULL,
  status_type_id int(11) NOT NULL,
  status_type_sub varchar(100) NOT NULL,
  status_type_sub_ref varchar(100) NOT NULL,
  created_by varchar(30) NOT NULL,
  created_time datetime NOT NULL DEFAULT current_timestamp(),
  updated_by varchar(30) DEFAULT NULL,
  updated_time datetime DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (status_type_sub_id),
  KEY status_type_id (status_type_id),
  CONSTRAINT statustypesub_ibfk_1 FOREIGN KEY (status_type_id) REFERENCES statustype (status_type_id) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

`,
  addTenant: `
CREATE TABLE IF NOT EXISTS tenant (
  tenant_id int(6) NOT NULL AUTO_INCREMENT,
  tenant_name varchar(50) NOT NULL,
  tenant_domain varchar(255) NOT NULL,
  created_time timestamp NOT NULL DEFAULT current_timestamp(),
  created_by varchar(30) NOT NULL DEFAULT 'ADMIN',
  updated_time timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  updated_by varchar(30) DEFAULT NULL,
  tenant_app_name varchar(100) DEFAULT NULL,
  tenant_app_logo varchar(255) DEFAULT NULL,
  tenant_app_font varchar(50) DEFAULT NULL,
  tenant_app_themes longtext DEFAULT NULL,
  PRIMARY KEY (tenant_id)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

`,
  addTreatment: `CREATE TABLE IF NOT EXISTS treatment (
  treatment_id int(11) NOT NULL AUTO_INCREMENT,
  tenant_id int(6) NOT NULL,
  patient_id int(11) NOT NULL,
  dentist_id int(11) NOT NULL,
  clinic_id int(11) NOT NULL,
  diagnosis text DEFAULT NULL,
  treatment_procedure text DEFAULT NULL,
  treatment_type enum('general','cosmetic','orthodontic','surgical','emergency') NOT NULL,
  treatment_status enum('planned','ongoing','completed','cancelled') NOT NULL,
  treatment_date date NOT NULL,
  cost decimal(10,2) NOT NULL,
  duration varchar(50) NOT NULL,
  teeth_involved varchar(255) NOT NULL,
  complications text DEFAULT NULL,
  follow_up_required tinyint(1) NOT NULL DEFAULT 0,
  follow_up_date date DEFAULT NULL,
  follow_up_notes text DEFAULT NULL,
  anesthesia_used tinyint(1) NOT NULL DEFAULT 0,
  anesthesia_type varchar(100) DEFAULT NULL,
  technician_assisted varchar(255) DEFAULT NULL,
  treatment_images varchar(255) DEFAULT NULL,
  notes text DEFAULT NULL,
  created_by varchar(30) NOT NULL,
  created_time timestamp NOT NULL DEFAULT current_timestamp(),
  updated_by varchar(30) DEFAULT NULL,
  updated_time timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (treatment_id),
  KEY fk_treatment_patient (patient_id),
  KEY fk_treatment_dentist (dentist_id),
  KEY fk_treatment_clinic (clinic_id),
  KEY fk_treatment_tenant (tenant_id),
  CONSTRAINT fk_treatment_clinic FOREIGN KEY (clinic_id) REFERENCES clinic (clinic_id) ON UPDATE CASCADE,
  CONSTRAINT fk_treatment_dentist FOREIGN KEY (dentist_id) REFERENCES dentist (dentist_id) ON UPDATE CASCADE,
  CONSTRAINT fk_treatment_patient FOREIGN KEY (patient_id) REFERENCES patient (patient_id) ON UPDATE CASCADE,
  CONSTRAINT fk_treatment_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

`,
addExpense: `
CREATE TABLE IF NOT EXISTS expense (
  expense_id INT(11) NOT NULL AUTO_INCREMENT,
  tenant_id INT(6) NOT NULL,
  clinic_id INT(11) NOT NULL,
  expense_amount DECIMAL(10,2) NULL,
  expense_category VARCHAR(255) NULL,
  expense_reason VARCHAR(255) NULL,
  expense_date DATE NULL,
  mode_of_payment VARCHAR(255) NULL,
  receipt_number VARCHAR(100) NULL,
  created_by VARCHAR(30) NOT NULL,
  created_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  updated_by VARCHAR(30) DEFAULT NULL,
  updated_time DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (expense_id),
  CONSTRAINT fk_expense_clinic FOREIGN KEY (clinic_id) REFERENCES clinic(clinic_id) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
`

};

module.exports = { createTableQuery };
