const createTableQuery = {
  addAppointment: `CREATE TABLE IF NOT EXISTS appointment (
  appointment_id int(11) NOT NULL AUTO_INCREMENT,
  tenant_id int(6) NOT NULL,
  patient_id int(11) NOT NULL,
  dentist_id int(11) NOT NULL,
  clinic_id int(11) NOT NULL,
  room_id char(36) DEFAULT '00000000-0000-0000-0000-000000000000' COMMENT 'UUID of assigned room',
  appointment_date date NOT NULL,
  start_time time NOT NULL,
  end_time time NOT NULL,
  status enum('pending','confirmed','checkedin','inprogress','completed','cancelled','clinic_cancelled','noshow','rescheduled','followup','rejected','expired','payment_pending','paid') NOT NULL DEFAULT 'pending',
  appointment_type enum('video','audio') DEFAULT NULL,
  doctor_rating decimal(3,2) DEFAULT NULL,
  feedback text DEFAULT NULL,
  consultation_fee decimal(10,2) DEFAULT 0.00,
  discount_applied decimal(6,2) NULL DEFAULT 0.00,
  payment_status varchar(100) NULL,
  min_booking_fee int(11) DEFAULT 0,
  paid_amount int(11) DEFAULT 0,
  rescheduled_from int(11) DEFAULT NULL,
  cancelled_by varchar(30) DEFAULT NULL,
  cancellation_reason text DEFAULT NULL,
  is_virtual tinyint(1) DEFAULT 0,
  reminder_send tinyint(1) DEFAULT 0,
  feedback_display tinyint(1) DEFAULT 1,
  meeting_link varchar(255) DEFAULT NULL,
  checkin_time datetime DEFAULT NULL,
  checkout_time datetime DEFAULT NULL,
  mode_of_payment varchar(100) NOT NULL,
  visit_reason text DEFAULT NULL,
  follow_up_needed tinyint(1) NOT NULL DEFAULT 0,
  reminder_method varchar(100) DEFAULT NULL,
  notes text DEFAULT NULL,
  created_by varchar(30) NOT NULL,
  created_time timestamp NOT NULL DEFAULT current_timestamp(),
  updated_by varchar(30) DEFAULT NULL,
  updated_time timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (appointment_id),
  KEY fk_appointment_tenant (tenant_id),
  KEY fk_appointment_patient (patient_id),
  KEY fk_appointment_dentist (dentist_id),
  KEY fk_appointment_clinic (clinic_id),
  CONSTRAINT fk_appointment_clinic FOREIGN KEY (clinic_id) REFERENCES clinic (clinic_id) ON UPDATE CASCADE,
  CONSTRAINT fk_appointment_dentist FOREIGN KEY (dentist_id) REFERENCES dentist (dentist_id) ON UPDATE CASCADE,
  CONSTRAINT fk_appointment_patient FOREIGN KEY (patient_id) REFERENCES patient (patient_id) ON UPDATE CASCADE,
  CONSTRAINT fk_appointment_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id)  ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;`,

  addAppointmentStats: `CREATE TABLE IF NOT EXISTS appointment_stats (
    appointment_stats_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    tenant_id INT NOT NULL,
    clinic_id INT NOT NULL,
    dentist_id INT NULL,
    stat_date DATE NOT NULL,
    confirmed INT DEFAULT 0,
    completed INT DEFAULT 0,
    cancelled INT DEFAULT 0,
    created_by varchar(30) NOT NULL DEFAULT 'ADMIN',
  created_time timestamp NOT NULL DEFAULT current_timestamp(),
  updated_by varchar(30) DEFAULT NULL,
  updated_time timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
    UNIQUE KEY uk_tenant_date (tenant_id,clinic_id,dentist_id, stat_date)
);`,

  addAsset: `CREATE TABLE IF NOT EXISTS asset (
  asset_id int(11) NOT NULL AUTO_INCREMENT,
  tenant_id int(6) NOT NULL,
  clinic_id int(11) NOT NULL,
  asset_name varchar(100) NOT NULL,
  asset_status varchar(50) DEFAULT NULL,
  asset_type varchar(50) DEFAULT NULL,
  asset_photo varchar(255) DEFAULT NULL,
  quantity int(4) DEFAULT NULL,
  price decimal(10,2) DEFAULT NULL,
  allocated_to varchar(100) DEFAULT NULL,
  purchased_date date DEFAULT NULL,
  purchased_by varchar(50) NOT NULL,
  expired_date date DEFAULT NULL,
  invoice_number varchar(16) DEFAULT NULL,
  description text DEFAULT NULL,
  created_by varchar(30) NOT NULL DEFAULT 'ADMIN',
  created_time timestamp NOT NULL DEFAULT current_timestamp(),
  updated_by varchar(30) DEFAULT NULL,
  updated_time timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (asset_id),
  KEY fk_asset_clinic (clinic_id),
  KEY fk_asset_tenant (tenant_id),
  CONSTRAINT fk_asset_clinic FOREIGN KEY (clinic_id) REFERENCES clinic (clinic_id) ON UPDATE CASCADE,
  CONSTRAINT fk_asset_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id) ON UPDATE CASCADE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

`,

  addClinic: `CREATE TABLE IF NOT EXISTS clinic (
  clinic_id int(11) NOT NULL AUTO_INCREMENT,
  tenant_id int(6) NOT NULL,
  clinic_name varchar(100) NOT NULL,
  email varchar(255) DEFAULT NULL,
  phone_number varchar(20) NOT NULL,
  alternate_phone_number varchar(20) DEFAULT NULL,
  branch varchar(50) DEFAULT NULL,
  website varchar(255) DEFAULT NULL,
  address text NOT NULL,
  city varchar(100) NOT NULL,
  state varchar(100) NOT NULL,
  country varchar(50) NOT NULL,
  pin_code varchar(6) NOT NULL,
  license_number varchar(10) NOT NULL,
  gst_number varchar(15) DEFAULT NULL,
  pan_number varchar(10) DEFAULT NULL,
  established_year int(4) NOT NULL,
  total_doctors int(3) DEFAULT 0,
  total_patients int(11) DEFAULT 0,
  seating_capacity int(4) DEFAULT 0,
  number_of_assistants int(4) DEFAULT 0,
  available_services longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(available_services)),
  operating_hours longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(operating_hours)),
  insurance_supported tinyint(1) NOT NULL DEFAULT 0,
  ratings decimal(3,2) DEFAULT 0.00,
  reviews_count int(11) DEFAULT 0,
  emergency_support tinyint(1) NOT NULL DEFAULT 0,
  teleconsultation_supported tinyint(1) NOT NULL DEFAULT 0,
  clinic_logo varchar(255) DEFAULT NULL,
  parking_availability tinyint(1) NOT NULL DEFAULT 0,
  pharmacy tinyint(1) NOT NULL DEFAULT 0,
  wifi tinyint(1) NOT NULL DEFAULT 0,
  clinic_app_font varchar(50) DEFAULT NULL,
  clinic_app_themes varchar(50) DEFAULT NULL,
  created_by varchar(30) NOT NULL DEFAULT 'ADMIN',
  created_time timestamp NOT NULL DEFAULT current_timestamp(),
  updated_by varchar(30) DEFAULT NULL,
  updated_time timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (clinic_id),
  KEY fk_tenant (tenant_id),
  KEY idx_phone_number (phone_number),
  CONSTRAINT fk_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id)  ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
`,

  addDentist: `CREATE TABLE IF NOT EXISTS dentist (
  dentist_id int(11) NOT NULL AUTO_INCREMENT,
  tenant_id int(6) NOT NULL,
  clinic_id int(11) NOT NULL,
  keycloak_id char(36) DEFAULT NULL,
  username varchar(50) DEFAULT NULL,
  password varchar(255) DEFAULT NULL,
  first_name varchar(50) NOT NULL,
  last_name varchar(50) NOT NULL,
  gender enum('M','F','TG') DEFAULT 'M',
  date_of_birth date DEFAULT NULL,
  email varchar(255) DEFAULT NULL,
  phone_number varchar(20) NOT NULL,
  alternate_phone_number varchar(20) DEFAULT NULL,
  specialisation varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  designation varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  member_of longtext DEFAULT NULL,
  experience_years int(2) NOT NULL,
  license_number varchar(20) NOT NULL,
  city varchar(100) NOT NULL,
  state varchar(100) NOT NULL,
  country varchar(50) NOT NULL,
  pin_code varchar(6) NOT NULL,
  working_hours longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(working_hours)),
  available_days longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(available_days)),
  consultation_fee decimal(10,2) DEFAULT 0.00,
  currency_code varchar(10) NULL DEFAULT NULL,
  min_booking_fee decimal(6,2) DEFAULT 0.00,
  ratings decimal(3,2) DEFAULT 0.00,
  reviews_count int(11) DEFAULT 0,
  appointment_count int(11) DEFAULT 0,
  profile_picture varchar(255) DEFAULT NULL,
  bio longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(bio)),
  teleconsultation_supported tinyint(1) NOT NULL DEFAULT 0,
  languages_spoken longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(languages_spoken)),
  awards_certifications longtext DEFAULT NULL,
  social_links longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  internship longtext DEFAULT NULL,
  position_held longtext DEFAULT NULL,
  research_projects longtext DEFAULT NULL,
  publication longtext DEFAULT NULL,
  social_activities longtext DEFAULT NULL,
  last_login timestamp NULL DEFAULT NULL,
  duration int(3) DEFAULT NULL,
  status tinyint(1) DEFAULT 1,
  created_by varchar(30) NOT NULL,
  created_time timestamp NOT NULL DEFAULT current_timestamp(),
  updated_by varchar(30) DEFAULT NULL,
  updated_time timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (dentist_id),
  KEY idx_dentist_keycloak_id (keycloak_id),
  KEY idx_tenant_id (tenant_id),
  KEY idx_phone_number (phone_number),
  KEY clinic_id (clinic_id),
  CONSTRAINT fk_dentist_clinic FOREIGN KEY (clinic_id) REFERENCES clinic (clinic_id)  ON UPDATE CASCADE,
  CONSTRAINT fk_dentist_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id)  ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
`,

  addPatient: `CREATE TABLE IF NOT EXISTS patient (
  patient_id int(11) NOT NULL AUTO_INCREMENT,
  tenant_id int(6) NOT NULL,
  keycloak_id char(36) DEFAULT NULL,
  username varchar(50) DEFAULT NULL,
  password varchar(255) DEFAULT NULL,
  first_name varchar(50) NOT NULL,
  last_name varchar(50) NOT NULL,
  email varchar(255) DEFAULT NULL,
  phone_number varchar(20) NOT NULL,
  alternate_phone_number varchar(20) DEFAULT NULL,
  date_of_birth date NOT NULL,
  gender enum('M','F','TG') NOT NULL DEFAULT 'M',
  blood_group varchar(10) DEFAULT NULL,
  address text NOT NULL,
  city varchar(100) NOT NULL,
  state varchar(100) NOT NULL,
  country varchar(50) NOT NULL,
  pin_code varchar(6) NOT NULL,
  pre_history text DEFAULT NULL,
  current_medications text DEFAULT NULL,
  dentist_preference int(11) DEFAULT NULL,
  smoking_status varchar(100) NOT NULL,
  alcohol_consumption varchar(100) NOT NULL,
  emergency_contact_name varchar(255) NOT NULL,
  emergency_contact_number varchar(15) NOT NULL,
  insurance_provider varchar(255) DEFAULT NULL,
  insurance_policy_number varchar(10) DEFAULT NULL,
  insurance_policy_start_date Date DEFAULT NULL,
  insurance_policy_end_date Date DEFAULT NULL,
  treatment_history longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(treatment_history)),
  appointment_count int(11) DEFAULT NULL,
  last_appointment_date timestamp NULL DEFAULT NULL,
  profile_picture varchar(255) DEFAULT NULL,
  created_by varchar(30) NOT NULL,
  created_time timestamp NOT NULL DEFAULT current_timestamp(),
  updated_by varchar(30) DEFAULT NULL,
  updated_time timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  first_visit_date timestamp NULL DEFAULT NULL,
  referred_by varchar(100) DEFAULT NULL,
  profession varchar(100) DEFAULT NULL,
  tooth_details text DEFAULT NULL,
  PRIMARY KEY (patient_id),
  KEY idx_patient_keycloak_id (keycloak_id),
  KEY fk_patient_tenant (tenant_id),
  KEY fk_patient_dentist (dentist_preference),
  CONSTRAINT fk_patient_dentist FOREIGN KEY (dentist_preference) REFERENCES dentist (dentist_id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_patient_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id)  ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
`,

  addPrescription: `CREATE TABLE IF NOT EXISTS prescription (
  prescription_id int(11) NOT NULL AUTO_INCREMENT,
  tenant_id int(6) NOT NULL,
  clinic_id int(11) NOT NULL,
  patient_id int(11) NOT NULL,
  dentist_id int(11) NOT NULL,
  treatment_id int(11) NOT NULL,
  medication text DEFAULT NULL,
  generic_name varchar(255) DEFAULT NULL,
  brand_name varchar(255) DEFAULT NULL,
  dosage int(4) DEFAULT 0,
  frequency varchar(50) DEFAULT NULL,
  quantity int(11) DEFAULT 0,
  refill_allowed tinyint(1) DEFAULT 0,
  refill_count int(11) DEFAULT 0,
  side_effects text DEFAULT NULL,
  start_date date DEFAULT NULL,
  end_date date DEFAULT NULL,
  instructions text DEFAULT NULL,
  notes text DEFAULT NULL,
  is_active tinyint(1) NOT NULL DEFAULT 1,
  created_by varchar(30) NOT NULL,
  created_time timestamp NOT NULL DEFAULT current_timestamp(),
  updated_by varchar(30) DEFAULT NULL,
  updated_time timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (prescription_id),
  KEY fk_prescription_patient (patient_id),
  KEY fk_prescription_dentist (dentist_id),
  KEY fk_prescription_treatment (treatment_id),
  KEY fk_prescription_tenant (tenant_id),
  KEY fk_prescription_clinic (clinic_id),
  CONSTRAINT fk_prescription_clinic FOREIGN KEY (clinic_id) REFERENCES clinic (clinic_id) ON UPDATE CASCADE,
  CONSTRAINT fk_prescription_dentist FOREIGN KEY (dentist_id) REFERENCES dentist (dentist_id) ON UPDATE CASCADE,
  CONSTRAINT fk_prescription_patient FOREIGN KEY (patient_id) REFERENCES patient (patient_id) ON UPDATE CASCADE,
  CONSTRAINT fk_prescription_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id)  ON UPDATE CASCADE,
  CONSTRAINT fk_prescription_treatment FOREIGN KEY (treatment_id) REFERENCES treatment (treatment_id) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
`,

  addStatusType: `
 CREATE TABLE IF NOT EXISTS statustype (
  status_type_id int(11) NOT NULL AUTO_INCREMENT,
  status_type varchar(100) NOT NULL,
  created_by varchar(30) NOT NULL,
  created_time timestamp NOT NULL DEFAULT current_timestamp(),
  updated_by varchar(30) DEFAULT NULL,
  updated_time timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (status_type_id),
  UNIQUE KEY status_type (status_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
`,
  addStatusTypeSub: `
CREATE TABLE IF NOT EXISTS statustypesub (
  status_type_sub_id int(11) NOT NULL AUTO_INCREMENT,
  tenant_id int(6) NOT NULL,
  status_type_id int(11) NOT NULL,
  status_type_sub varchar(100) NOT NULL,
  status_type_sub_ref varchar(100) NOT NULL,
  created_by varchar(30) NOT NULL,
  created_time timestamp NOT NULL DEFAULT current_timestamp(),
  updated_by varchar(30) DEFAULT NULL,
  updated_time timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (status_type_sub_id),
  KEY status_type_id (status_type_id),
  CONSTRAINT statustypesub_ibfk_1 FOREIGN KEY (status_type_id) REFERENCES statustype (status_type_id) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
`,
  addTenant: `
CREATE TABLE IF NOT EXISTS tenant (
  tenant_id int(6) NOT NULL AUTO_INCREMENT,
  tenant_name varchar(50) NOT NULL,
  tenant_domain varchar(255) NOT NULL,
  created_time timestamp NOT NULL DEFAULT current_timestamp(),
  created_by varchar(30) NOT NULL DEFAULT 'ADMIN',
  updated_time timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  updated_by varchar(30) DEFAULT NULL,
  tenant_app_name varchar(100) DEFAULT NULL,
  tenant_app_logo varchar(255) DEFAULT NULL,
  tenant_app_font varchar(50) DEFAULT NULL,
  tenant_app_themes varchar(50) DEFAULT NULL,
  PRIMARY KEY (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
`,
  addTreatment: `CREATE TABLE IF NOT EXISTS treatment (
  treatment_id int(11) NOT NULL AUTO_INCREMENT,
  tenant_id int(6) NOT NULL,
  appointment_id int(11) NOT NULL,
  patient_id int(11) NOT NULL,
  dentist_id int(11) NOT NULL,
  clinic_id int(11) NOT NULL,
  diagnosis text DEFAULT NULL,
  treatment_procedure text DEFAULT NULL,
  treatment_type varchar(100) NOT NULL,
  treatment_status varchar(100) NOT NULL,
  treatment_date date NOT NULL,
  cost decimal(10,2) NOT NULL DEFAULT 0.00,
  duration varchar(50) NOT NULL,
  teeth_involved varchar(255) NOT NULL,
  complications text DEFAULT NULL,
  follow_up_required tinyint(1) NOT NULL DEFAULT 0,
  follow_up_date date DEFAULT NULL,
  follow_up_notes text DEFAULT NULL,
  anesthesia_used tinyint(1) NOT NULL DEFAULT 0,
  anesthesia_type varchar(100) DEFAULT NULL,
  technician_assisted varchar(255) DEFAULT NULL,
  treatment_images longtext DEFAULT NULL,
  notes text DEFAULT NULL,
  created_by varchar(30) NOT NULL,
  created_time timestamp NOT NULL DEFAULT current_timestamp(),
  updated_by varchar(30) DEFAULT NULL,
  updated_time timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (treatment_id),
  KEY fk_treatment_appointment (appointment_id),
  KEY fk_treatment_patient (patient_id),
  KEY fk_treatment_dentist (dentist_id),
  KEY fk_treatment_clinic (clinic_id),
  KEY fk_treatment_tenant (tenant_id),
  CONSTRAINT fk_treatment_appointment FOREIGN KEY (appointment_id) REFERENCES appointment (appointment_id) ON UPDATE CASCADE,
  CONSTRAINT fk_treatment_clinic FOREIGN KEY (clinic_id) REFERENCES clinic (clinic_id) ON UPDATE CASCADE,
  CONSTRAINT fk_treatment_dentist FOREIGN KEY (dentist_id) REFERENCES dentist (dentist_id) ON UPDATE CASCADE,
  CONSTRAINT fk_treatment_patient FOREIGN KEY (patient_id) REFERENCES patient (patient_id) ON UPDATE CASCADE,
  CONSTRAINT fk_treatment_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id)  ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
`,
  addExpense: `
CREATE TABLE IF NOT EXISTS expense (
  expense_id int(11) NOT NULL AUTO_INCREMENT,
  tenant_id int(6) NOT NULL,
  clinic_id int(11) NOT NULL,
  expense_amount decimal(10,2) DEFAULT 0.00,
  expense_category varchar(255) DEFAULT NULL,
  expense_reason varchar(255) DEFAULT NULL,
  expense_date date DEFAULT NULL,
  mode_of_payment varchar(100) DEFAULT NULL,
  receipt_number varchar(100) DEFAULT NULL,
  paid_by varchar(100) DEFAULT NULL,
  paid_by_user varchar(100) DEFAULT NULL,
  expense_documents longtext DEFAULT NULL,
  paid_to varchar(100) DEFAULT NULL,
  created_by varchar(30) NOT NULL,
  created_time timestamp NOT NULL DEFAULT current_timestamp(),
  updated_by varchar(30) DEFAULT NULL,
  updated_time timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (expense_id),
  KEY fk_expense_clinic (clinic_id),
  KEY fk_expense_tenant (tenant_id),
  CONSTRAINT fk_expense_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id) ON UPDATE CASCADE,
  CONSTRAINT fk_expense_clinic FOREIGN KEY (clinic_id) REFERENCES clinic (clinic_id) ON UPDATE CASCADE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
`,
  addSupplier: `
CREATE TABLE IF NOT EXISTS supplier (
  supplier_id INT(11) NOT NULL AUTO_INCREMENT,
  supplier_code VARCHAR(50) DEFAULT NULL,
  tenant_id INT(6) NOT NULL,
  clinic_id INT(11) NOT NULL,
  keycloak_id CHAR(36) DEFAULT NULL,
  username VARCHAR(50) DEFAULT NULL,
  password VARCHAR(255) DEFAULT NULL,
  name VARCHAR(100) DEFAULT NULL,
  category VARCHAR(100) DEFAULT NULL,
  status TINYINT(1) DEFAULT 1,
  email VARCHAR(150) DEFAULT NULL,
  phone_number VARCHAR(20) NOT NULL,
  alternate_phone_number VARCHAR(20) NOT NULL,
  fax VARCHAR(50) DEFAULT NULL,
  website VARCHAR(255) DEFAULT NULL,
  gst_number VARCHAR(50) DEFAULT NULL,
  tax_id VARCHAR(50) DEFAULT NULL,
  pan_number VARCHAR(50) DEFAULT NULL,
  logo_url TEXT DEFAULT NULL,
  mode_of_payment VARCHAR(100) DEFAULT NULL,
  preferred_currency VARCHAR(10) DEFAULT NULL,
  credit_limit DECIMAL(15, 2) DEFAULT NULL,
  opening_balance DECIMAL(15, 2) DEFAULT NULL,
  notes TEXT DEFAULT NULL,
  address_type ENUM('billing','shipping','office') DEFAULT 'billing',
  address Varchar(100) DEFAULT NULL,
  city Varchar(100) DEFAULT NULL,
  state Varchar(100) DEFAULT NULL,
  postal_code Varchar(20) DEFAULT NULL,
  country Varchar(100) DEFAULT NULL,
  created_by VARCHAR(30) NOT NULL,
  created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  updated_by VARCHAR(30) DEFAULT NULL,
  updated_time TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(),
  
  PRIMARY KEY (supplier_id),
  KEY idx_supplier_keycloak_id (keycloak_id),
  UNIQUE KEY uq_supplier_code (supplier_code),
  KEY fk_supplier_clinic (clinic_id),
  KEY fk_supplier_tenant (tenant_id),
  CONSTRAINT fk_supplier_clinic FOREIGN KEY (clinic_id) REFERENCES clinic (clinic_id) ON UPDATE CASCADE,
  CONSTRAINT fk_supplier_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

`,
  addSupplierProducts: `
CREATE TABLE IF NOT EXISTS supplier_products (
  supplier_product_id INT(11) NOT NULL AUTO_INCREMENT,
  tenant_id INT(6) NOT NULL,
  clinic_id INT(11) NOT NULL,
  supplier_id INT(11) NOT NULL,
  product_name VARCHAR(255) DEFAULT NULL,
  image_url VARCHAR(255) DEFAULT NULL,
  description TEXT DEFAULT NULL,
  unit_price DECIMAL(15, 2) DEFAULT NULL,
  unit VARCHAR(50) DEFAULT NULL,
  moq INT DEFAULT NULL,
  lead_time_days INT DEFAULT NULL,
  currency VARCHAR(10) DEFAULT NULL,
  active TINYINT(1) DEFAULT 1,
  created_by VARCHAR(30) NOT NULL,
  created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  updated_by VARCHAR(30) DEFAULT NULL,
  updated_time TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(),

  PRIMARY KEY (supplier_product_id),
  KEY fk_supplier_product_supplier (supplier_id),
  KEY fk_supplier_product_tenant (tenant_id),
  KEY fk_supplier_product_clinic (clinic_id),

  CONSTRAINT fk_supplier_product_supplier FOREIGN KEY (supplier_id)
    REFERENCES supplier (supplier_id)  ON UPDATE CASCADE,
  CONSTRAINT fk_supplier_product_tenant FOREIGN KEY (tenant_id)
    REFERENCES tenant (tenant_id)  ON UPDATE CASCADE,
  CONSTRAINT fk_supplier_product_clinic FOREIGN KEY (clinic_id)
    REFERENCES clinic (clinic_id)  ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

`,
  addPurchaseOrder: `CREATE TABLE IF NOT EXISTS purchase_orders (
  purchase_order_id INT(11) NOT NULL AUTO_INCREMENT,
  tenant_id INT(6) NOT NULL,
  clinic_id INT(11) NOT NULL,
  dentist_id INT(11) NULL,
  supplier_id INT(11) NOT NULL,
  supplier_product_id INT(11) NOT NULL,
  order_number VARCHAR(100) DEFAULT NULL,
  order_date DATE DEFAULT NULL,
  product_name VARCHAR(100) DEFAULT NULL,
  quantity INT DEFAULT NULL,
  total_amount DECIMAL(12,2) DEFAULT NULL,
  status ENUM('pending', 'confirmed', 'shipped', 'delivered', 'cancelled') DEFAULT 'pending',
  delivery_date DATE DEFAULT NULL,
  created_by VARCHAR(30) NOT NULL,
  created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  updated_by VARCHAR(30) DEFAULT NULL,
  updated_time TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(),

  PRIMARY KEY (purchase_order_id),
  KEY fk_purchase_order_supplier (supplier_id),
  KEY fk_purchase_order_supplier_product (supplier_product_id),
  KEY fk_purchase_order_tenant (tenant_id),
  KEY fk_purchase_order_clinic (clinic_id),
  KEY fk_purchase_order_dentist (dentist_id),

  CONSTRAINT fk_purchase_order_supplier FOREIGN KEY (supplier_id)
    REFERENCES supplier (supplier_id)  ON UPDATE CASCADE,
  CONSTRAINT fk_purchase_order_tenant FOREIGN KEY (tenant_id)
    REFERENCES tenant (tenant_id)  ON UPDATE CASCADE,
  CONSTRAINT fk_purchase_order_clinic FOREIGN KEY (clinic_id)
    REFERENCES clinic (clinic_id)  ON UPDATE CASCADE,
  CONSTRAINT fk_purchase_order_dentist FOREIGN KEY (dentist_id)
    REFERENCES dentist (dentist_id)  ON UPDATE CASCADE,
  CONSTRAINT fk_purchase_order_supplier_product FOREIGN KEY (supplier_product_id)
    REFERENCES supplier_products (supplier_product_id)  ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
`,
  addSupplierPayments: `CREATE TABLE IF NOT EXISTS supplier_payments (
  supplier_payment_id INT(11) NOT NULL AUTO_INCREMENT,
  tenant_id INT(6) NOT NULL,
  clinic_id INT(11) NOT NULL,
  supplier_id INT(11) NOT NULL,
  purchase_order_id INT(11) NOT NULL,
  amount DECIMAL(12, 2) NOT NULL,
  paid_amount DECIMAL(12, 2) NULL DEFAULT 0,
  balance_amount DECIMAL(12, 2) NULL DEFAULT 0,
  supplier_payment_documents text NULL,
  mode_of_payment VARCHAR(50) DEFAULT NULL,
  receipt_number VARCHAR(100) DEFAULT NULL,
  bank_name VARCHAR(100) DEFAULT NULL,
  bank_account_number VARCHAR(100) DEFAULT NULL,
  bank_ifsc VARCHAR(20) DEFAULT NULL,
  transaction_id VARCHAR(100) DEFAULT NULL,
  payment_date DATE DEFAULT NULL,
  created_by VARCHAR(30) NOT NULL,
  created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  updated_by VARCHAR(30) DEFAULT NULL,
  updated_time TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(),

  PRIMARY KEY (supplier_payment_id),
  KEY fk_supplier_payment_supplier (supplier_id),
  KEY fk_supplier_payment_purchase_order (purchase_order_id),
  KEY fk_supplier_payment_tenant (tenant_id),
  KEY fk_supplier_payment_clinic (clinic_id),

  CONSTRAINT fk_supplier_payment_supplier FOREIGN KEY (purchase_order_id)
    REFERENCES purchase_orders (purchase_order_id)  ON UPDATE CASCADE,
  CONSTRAINT fk_supplier_payment_purchase_order FOREIGN KEY (supplier_id)
    REFERENCES supplier (supplier_id)  ON UPDATE CASCADE,
  CONSTRAINT fk_supplier_payment_tenant FOREIGN KEY (tenant_id)
    REFERENCES tenant (tenant_id)  ON UPDATE CASCADE,
  CONSTRAINT fk_supplier_payment_clinic FOREIGN KEY (clinic_id)
    REFERENCES clinic (clinic_id)  ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
`,
  addSupplierReview: `CREATE TABLE IF NOT EXISTS supplier_reviews (
  supplier_review_id INT(11) NOT NULL AUTO_INCREMENT,
  tenant_id INT(6) NOT NULL,
  clinic_id INT(11) NOT NULL,
  supplier_id INT(11) NOT NULL,
  purchase_order_id INT(11) NOT NULL,
  rating_quality INT(1) CHECK (rating_quality BETWEEN 1 AND 5),
  rating_delivery INT(1) CHECK (rating_delivery BETWEEN 1 AND 5),
  rating_communication INT(1) CHECK (rating_communication BETWEEN 1 AND 5),
  comment TEXT DEFAULT NULL,
  reviewed_by VARCHAR(30) NOT NULL,
  created_by VARCHAR(30) NOT NULL,
  created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  updated_by VARCHAR(30) DEFAULT NULL,
  updated_time TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(),

  PRIMARY KEY (supplier_review_id),
  KEY fk_supplier_review_supplier (supplier_id),
  KEY fk_supplier_review_tenant (tenant_id),
  KEY fk_supplier_review_clinic (clinic_id),
  KEY fk_supplier_review_purchase_order (purchase_order_id),

  CONSTRAINT fk_supplier_review_supplier FOREIGN KEY (supplier_id)
    REFERENCES supplier (supplier_id)  ON UPDATE CASCADE,
  CONSTRAINT fk_supplier_review_tenant FOREIGN KEY (tenant_id)
    REFERENCES tenant (tenant_id)  ON UPDATE CASCADE,
  CONSTRAINT fk_supplier_review_clinic FOREIGN KEY (clinic_id)
    REFERENCES clinic (clinic_id)  ON UPDATE CASCADE,
  CONSTRAINT fk_supplier_review_purchase_order FOREIGN KEY (purchase_order_id)
    REFERENCES purchase_orders (purchase_order_id)  ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
`,
  addReminder: `
CREATE TABLE IF NOT EXISTS reminder (
  reminder_id int(11) NOT NULL AUTO_INCREMENT,
  tenant_id int(6) NOT NULL,
  clinic_id int(11) NOT NULL,
  dentist_id int(11) NOT NULL,
  title varchar(255) NOT NULL,
  description text DEFAULT NULL,
  reminder_repeat enum('daily','weekly','monthly','yearly') DEFAULT NULL,
  category varchar(100) DEFAULT NULL,
  reminder_type varchar(100) DEFAULT NULL,
  type enum('reminder','todo') NOT NULL,
  is_recurring tinyint(1) DEFAULT NULL,
  start_date date NOT NULL,
  time time NOT NULL,
  repeat_interval int(2) NOT NULL DEFAULT 1,
  repeat_count int(2) NOT NULL DEFAULT 0,
  repeat_weekdays varchar(20) DEFAULT NULL,
  monthly_week Text DEFAULT NULL,
  monthly_weekdays Text DEFAULT NULL,
  repeat_end_date date DEFAULT NULL,
  monthly_option varchar(20) DEFAULT NULL,
  notify tinyint(1) DEFAULT 0,
  notify_before_hours int(3) DEFAULT NULL,
  reminder_reason varchar(255) DEFAULT NULL,
  status varchar(20) DEFAULT NULL,
  created_by varchar(30) NOT NULL,
  created_time timestamp NOT NULL DEFAULT current_timestamp(),
  updated_by varchar(30) DEFAULT NULL,
  updated_time timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (reminder_id),
  KEY fk_reminder_clinic (clinic_id),
  KEY fk_reminder_tenant (tenant_id),
  KEY fk_reminder_dentist (dentist_id),
  CONSTRAINT fk_reminder_clinic FOREIGN KEY (clinic_id) REFERENCES clinic (clinic_id) ON UPDATE CASCADE,
  CONSTRAINT fk_reminder_dentist FOREIGN KEY (dentist_id) REFERENCES dentist (dentist_id) ON UPDATE CASCADE,
  CONSTRAINT fk_reminder_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id) ON UPDATE CASCADE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

`,
  addAppointmentReschedules: `
CREATE TABLE IF NOT EXISTS appointment_reschedules (
  rescheduled_id int(11) NOT NULL AUTO_INCREMENT,
  tenant_id int(6) NOT NULL,
  clinic_id int(11) NOT NULL,
  dentist_id int(11) NOT NULL,
  original_appointment_id int(11) NOT NULL,
  new_appointment_id int(11) NOT NULL,
  previous_date date NOT NULL,
  previous_time time NOT NULL,
  new_date date NOT NULL,
  new_start_time time NOT NULL,
  new_end_time time NOT NULL,
  reason text NOT NULL,
  charge_applicable tinyint(1) NOT NULL DEFAULT 0,
  charge_amount decimal(10,2) NOT NULL DEFAULT 0.00,
  rescheduled_by varchar(30) NOT NULL,
  rescheduled_at timestamp NULL DEFAULT NULL,
  created_by varchar(30) NOT NULL,
  created_time timestamp NOT NULL DEFAULT current_timestamp(),
  updated_by varchar(30) DEFAULT NULL,
  updated_time timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (rescheduled_id),
  KEY fk_appointment_reschedules_clinic (clinic_id),
  KEY fk_appointment_reschedules_tenant (tenant_id),
  KEY fk_appointment_reschedules_dentist (dentist_id),
  CONSTRAINT fk_appointment_reschedules_clinic FOREIGN KEY (clinic_id) REFERENCES clinic (clinic_id) ON UPDATE CASCADE,
  CONSTRAINT fk_appointment_reschedules_dentist FOREIGN KEY (dentist_id) REFERENCES dentist (dentist_id) ON UPDATE CASCADE,
  CONSTRAINT fk_appointment_reschedules_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id) ON UPDATE CASCADE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

`,
  addPayment: `
CREATE TABLE IF NOT EXISTS payment (
  payment_id int(11) NOT NULL AUTO_INCREMENT,
  tenant_id int(6) NOT NULL,
  clinic_id int(11) NOT NULL,
  patient_id int(11) NOT NULL,
  dentist_id int(11) NOT NULL,
  appointment_id int(11) NOT NULL,
  amount decimal(10,2) NOT NULL DEFAULT 0.00,
  discount_applied decimal(10,2) DEFAULT 0.00,
  final_amount decimal(10,2) NOT NULL DEFAULT 0.00,
  mode_of_payment varchar(100) NOT NULL,
  payment_source varchar(100) NOT NULL,
  payment_reference varchar(255) DEFAULT NULL,
  payment_status varchar(100) NOT NULL,
  payment_verified tinyint(1) DEFAULT 0,
  receipt_number varchar(25) DEFAULT NULL,
  insurance_number varchar(25) DEFAULT NULL,
  payment_date datetime DEFAULT NULL,
  created_by varchar(30) NOT NULL,
  created_time timestamp NOT NULL DEFAULT current_timestamp(),
  updated_by varchar(30) DEFAULT NULL,
  updated_time timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (payment_id),
  KEY fk_payment_tenant (tenant_id),
  KEY fk_payment_clinic (clinic_id),
  KEY fk_payment_patient (patient_id),
  KEY fk_payment_dentist (dentist_id),
  KEY fk_payment_appointment (appointment_id),
  CONSTRAINT fk_payment_appointment FOREIGN KEY (appointment_id) REFERENCES appointment (appointment_id) ON UPDATE CASCADE,
  CONSTRAINT fk_payment_clinic FOREIGN KEY (clinic_id) REFERENCES clinic (clinic_id) ON UPDATE CASCADE,
  CONSTRAINT fk_payment_dentist FOREIGN KEY (dentist_id) REFERENCES dentist (dentist_id) ON UPDATE CASCADE,
  CONSTRAINT fk_payment_patient FOREIGN KEY (patient_id) REFERENCES patient (patient_id) ON UPDATE CASCADE,
  CONSTRAINT fk_payment_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

`,
  addReception: `CREATE TABLE IF NOT EXISTS reception (
  reception_id int(11) NOT NULL AUTO_INCREMENT,
  tenant_id int(6) NOT NULL,
  clinic_id int(11) NOT NULL,
  keycloak_id char(36) DEFAULT NULL,
  username varchar(50) DEFAULT NULL,
  password varchar(255) DEFAULT NULL,
  full_name varchar(100) NOT NULL,
  email varchar(255) DEFAULT NULL,
  phone_number varchar(20) NOT NULL,
  alternate_phone_number varchar(20) DEFAULT NULL,
  date_of_birth date NOT NULL,
  gender enum('M','F','TG') NOT NULL DEFAULT 'M',
  status tinyint(1) DEFAULT 1,
  address text NOT NULL,
  city varchar(100) NOT NULL,
  state varchar(100) NOT NULL,
  country varchar(50) NOT NULL,
  pincode varchar(6) NOT NULL,
  last_login datetime DEFAULT NULL,
  profile_picture varchar(255) DEFAULT NULL,
  created_by varchar(30) NOT NULL,
  created_time timestamp NOT NULL DEFAULT current_timestamp(),
  updated_by varchar(30) DEFAULT NULL,
  updated_time timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (reception_id),
  KEY idx_reception_keycloak_id (keycloak_id),
  KEY fk_reception_tenant (tenant_id),
  KEY fk_reception_clinic (clinic_id),
  CONSTRAINT fk_reception_clinic FOREIGN KEY (clinic_id) REFERENCES clinic (clinic_id) ON UPDATE CASCADE,
  CONSTRAINT fk_reception_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id) ON UPDATE CASCADE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
`,
  addToothDetails: `CREATE TABLE IF NOT EXISTS toothdetails (
  toothdetails_id int(11) NOT NULL AUTO_INCREMENT,
  tenant_id int(6) NOT NULL,
  clinic_id int(11) NOT NULL,
  dentist_id int(11) NOT NULL,
  patient_id int(11) NOT NULL,
  tooth_id TINYINT UNSIGNED NOT NULL,
  tooth_name varchar(100) NOT NULL,
  tooth_position varchar(100) NOT NULL,
  disease_type varchar(100) NOT NULL,
  disease_name varchar(100) NOT NULL,
  treatment_date Date NOT NULL,
  description text,
  created_by varchar(30) NOT NULL,
  created_time timestamp NOT NULL DEFAULT current_timestamp(),
  updated_by varchar(30) DEFAULT NULL,
  updated_time timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (toothdetails_id),
  KEY fk_toothdetails_dentist (dentist_id),
  KEY fk_toothdetails_patient (patient_id),
  KEY fk_toothdetails_tenant (tenant_id),
  KEY fk_toothdetails_clinic (clinic_id),
  KEY idx_toothdetails_treatment_date (treatment_date),
  CONSTRAINT fk_toothdetails_clinic FOREIGN KEY (clinic_id) REFERENCES clinic (clinic_id) ON UPDATE CASCADE,
  CONSTRAINT fk_toothdetails_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id) ON UPDATE CASCADE,
  CONSTRAINT fk_toothdetails_dentist FOREIGN KEY (dentist_id) REFERENCES dentist (dentist_id) ON UPDATE CASCADE,
  CONSTRAINT fk_toothdetails_patient FOREIGN KEY (patient_id) REFERENCES patient (patient_id) ON UPDATE CASCADE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
`,
  addLoginHistory: `CREATE TABLE IF NOT EXISTS loginhistory (
  loginhistory_id int(11) NOT NULL AUTO_INCREMENT,
  tenant_id int(11) DEFAULT NULL,
  clinic_id int(11) DEFAULT NULL,
  keycloak_user_id char(36) DEFAULT NULL,
  session_id varchar(36) DEFAULT NULL,
  login_time datetime DEFAULT NULL,
  logout_time datetime DEFAULT NULL,
  ip_address varchar(45) DEFAULT NULL,
  device_info text DEFAULT NULL,
  browser_info text DEFAULT NULL,
  created_time timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (loginhistory_id),
  KEY idx_loginhistory_keycloak_user_id (keycloak_user_id),
  KEY fk_login_history_clinic (clinic_id),
  KEY fk_login_history_tenant (tenant_id),
  CONSTRAINT fk_login_history_clinic FOREIGN KEY (clinic_id) REFERENCES clinic (clinic_id) ON UPDATE CASCADE,
  CONSTRAINT fk_login_history_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id) ON UPDATE CASCADE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

`,
  addUserActivity: `CREATE TABLE IF NOT EXISTS useractivity (
  useractivity_id int(11) NOT NULL AUTO_INCREMENT,
  keycloak_user_id char(36) DEFAULT NULL,
  ip_address varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  browser varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  device varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  login_time timestamp NULL DEFAULT current_timestamp(),
  logout_time timestamp NULL DEFAULT NULL,
  duration time DEFAULT NULL,
  created_time timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (useractivity_id),
  KEY idx_useractivity_keycloak_user_id (keycloak_user_id)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

`,
  addNotificationSend: `CREATE TABLE IF NOT EXISTS notifications (
  notification_id INT(11) NOT NULL AUTO_INCREMENT,

  tenant_id INT NOT NULL,
  sender_role VARCHAR(20) NOT NULL,
  sender_id INT NOT NULL, -- e.g., doctor_id, patient_id

  type VARCHAR(50) NOT NULL,
  -- Example values: 'treatment', 'document', 'message', 'appointment', 'reminder', 'invoice'

  title VARCHAR(255) NOT NULL,
  message TEXT,

  reference_id INT NULL DEFAULT NULL,
  -- Optional: link to treatment_id, appointment_id, etc.

  file_url TEXT,
  -- Optional: attached PDF, image, doc path or URL

  created_by VARCHAR(50),
  created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(50),
  updated_time TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,

  -- Primary Key required for AUTO_INCREMENT
  PRIMARY KEY (notification_id),

  -- Foreign Key Constraints
  CONSTRAINT fk_notification_tenant FOREIGN KEY (tenant_id)
    REFERENCES tenant(tenant_id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

`,
  addNotificationRecipients: `CREATE TABLE IF NOT EXISTS notificationrecipients (
  notification_recipient_id INT(11) NOT NULL AUTO_INCREMENT,

  notification_id INT NOT NULL,
  receiver_role VARCHAR(20) NOT NULL,
  receiver_id INT NOT NULL, -- e.g., doctor_id, patient_id

  status VARCHAR(50) NOT NULL DEFAULT 'unread',

  created_by VARCHAR(50),
  delivered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  read_at TIMESTAMP DEFAULT NULL,

  -- Set primary key for auto_increment
  PRIMARY KEY (notification_recipient_id),

  -- Correct foreign key reference
  CONSTRAINT fk_notification_recipients_notification FOREIGN KEY (notification_id)
    REFERENCES notifications(notification_id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

`,
};

module.exports = { createTableQuery };
