const createTableQuery = {
  addAppointment: `CREATE TABLE IF NOT EXISTS appointment (
    appointment_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    patient_id BIGINT UNSIGNED NOT NULL,
    dentist_id BIGINT UNSIGNED NOT NULL,
    clinic_id BIGINT UNSIGNED NOT NULL,
    room_id CHAR(36) DEFAULT '00000000-0000-0000-0000-000000000000' COMMENT 'UUID of assigned room',
    appointment_date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    status ENUM('pending','confirmed','checkedin','inprogress','completed','cancelled','clinic_cancelled','noshow','rescheduled','followup','rejected','expired','payment_pending','paid') NOT NULL DEFAULT 'pending',
    appointment_type ENUM('video','audio') DEFAULT NULL,
    doctor_rating DECIMAL(3,2) DEFAULT NULL,
    feedback TEXT DEFAULT NULL,
    consultation_fee DECIMAL(12,2) DEFAULT 0.00,
    discount_applied DECIMAL(12,2) DEFAULT 0.00,
    payment_status VARCHAR(100) DEFAULT NULL,
    min_booking_fee DECIMAL(12,2) DEFAULT 0.00,
    paid_amount DECIMAL(12,2) DEFAULT 0.00,
    rescheduled_from BIGINT UNSIGNED DEFAULT NULL,
    cancelled_by VARCHAR(30) DEFAULT NULL,
    cancellation_reason TEXT DEFAULT NULL,
    is_virtual TINYINT(1) DEFAULT 0,
    reminder_send TINYINT(1) DEFAULT 0,
    feedback_display TINYINT(1) DEFAULT 1,
    meeting_link VARCHAR(255) DEFAULT NULL,
    checkin_time DATETIME DEFAULT NULL,
    checkout_time DATETIME DEFAULT NULL,
    mode_of_payment VARCHAR(100) NOT NULL,
    visit_reason TEXT DEFAULT NULL,
    follow_up_needed TINYINT(1) NOT NULL DEFAULT 0,
    reminder_method VARCHAR(100) DEFAULT NULL,
    notes TEXT DEFAULT NULL,
    created_by VARCHAR(30) NOT NULL,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_by VARCHAR(30) DEFAULT NULL,
    updated_time TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (appointment_id),
    KEY fk_appointment_tenant (tenant_id),
    KEY fk_appointment_patient (patient_id),
    KEY fk_appointment_dentist (dentist_id),
    KEY fk_appointment_clinic (clinic_id),
    KEY idx_tenant_date_time_status (tenant_id, appointment_date, start_time, status),
    CONSTRAINT fk_appointment_clinic FOREIGN KEY (clinic_id) REFERENCES clinic (clinic_id) ON UPDATE CASCADE,
    CONSTRAINT fk_appointment_dentist FOREIGN KEY (dentist_id) REFERENCES dentist (dentist_id) ON UPDATE CASCADE,
    CONSTRAINT fk_appointment_patient FOREIGN KEY (patient_id) REFERENCES patient (patient_id) ON UPDATE CASCADE,
    CONSTRAINT fk_appointment_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id) ON UPDATE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;`,

  addAppointmentStats: `CREATE TABLE IF NOT EXISTS appointment_stats (
    appointment_stats_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    clinic_id BIGINT UNSIGNED NOT NULL,
    dentist_id BIGINT UNSIGNED DEFAULT NULL,
    stat_date DATE NOT NULL,
    confirmed INT DEFAULT 0,
    completed INT DEFAULT 0,
    cancelled INT DEFAULT 0,
    created_by VARCHAR(30) NOT NULL DEFAULT 'ADMIN',
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_by VARCHAR(30) DEFAULT NULL,
    updated_time TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (appointment_stats_id),
    UNIQUE KEY uk_tenant_date (tenant_id, clinic_id, dentist_id, stat_date)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;`,

  addAsset: `CREATE TABLE IF NOT EXISTS asset (
    asset_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    clinic_id BIGINT UNSIGNED NOT NULL,
    asset_name VARCHAR(100) NOT NULL,
    asset_status VARCHAR(50) DEFAULT NULL,
    asset_type VARCHAR(50) DEFAULT NULL,
    asset_photo VARCHAR(255) DEFAULT NULL,
    quantity INT DEFAULT NULL,
    price DECIMAL(12,2) DEFAULT NULL,
    allocated_to VARCHAR(100) DEFAULT NULL,
    purchased_date DATE DEFAULT NULL,
    purchased_by VARCHAR(50) NOT NULL,
    expired_date DATE DEFAULT NULL,
    invoice_number VARCHAR(50) DEFAULT NULL,
    description TEXT DEFAULT NULL,
    created_by VARCHAR(30) NOT NULL,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_by VARCHAR(30) DEFAULT NULL,
    updated_time TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (asset_id),
    KEY fk_asset_clinic (clinic_id),
    KEY fk_asset_tenant (tenant_id),
    CONSTRAINT fk_asset_clinic FOREIGN KEY (clinic_id) REFERENCES clinic (clinic_id) ON UPDATE CASCADE,
    CONSTRAINT fk_asset_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id) ON UPDATE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;`,

  addClinic: `CREATE TABLE IF NOT EXISTS clinic (
    clinic_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    clinic_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) DEFAULT NULL,
    phone_number VARCHAR(15) NOT NULL,
    alternate_phone_number VARCHAR(15) DEFAULT NULL,
    branch VARCHAR(50) DEFAULT NULL,
    website VARCHAR(255) DEFAULT NULL,
    address TEXT NOT NULL,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    country VARCHAR(50) NOT NULL,
    pin_code VARCHAR(10) NOT NULL,
    license_number VARCHAR(10) NOT NULL,
    gst_number VARCHAR(15) DEFAULT NULL,
    pan_number VARCHAR(10) DEFAULT NULL,
    clinic_logo VARCHAR(255) DEFAULT NULL,
    established_year INT NOT NULL,
    total_doctors INT DEFAULT 0,
    total_patients BIGINT UNSIGNED DEFAULT 0,
    seating_capacity INT DEFAULT 0,
    number_of_assistants INT DEFAULT 0,
    available_services LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(available_services)),
    operating_hours LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(operating_hours)),
    insurance_supported TINYINT(1) NOT NULL DEFAULT 0,
    ratings DECIMAL(3,2) DEFAULT 0.00,
    reviews_count INT DEFAULT 0,
    emergency_support TINYINT(1) NOT NULL DEFAULT 0,
    teleconsultation_supported TINYINT(1) NOT NULL DEFAULT 0,
    parking_availability TINYINT(1) NOT NULL DEFAULT 0,
    pharmacy TINYINT(1) NOT NULL DEFAULT 0,
    wifi TINYINT(1) NOT NULL DEFAULT 0,
    clinic_app_font VARCHAR(50) DEFAULT NULL,
    clinic_app_themes VARCHAR(50) DEFAULT NULL,
    created_by VARCHAR(30) NOT NULL DEFAULT 'ADMIN',
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_by VARCHAR(30) DEFAULT NULL,
    updated_time TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (clinic_id),
    KEY fk_clinic_tenant (tenant_id),
    KEY idx_phone_number (phone_number),
    CONSTRAINT fk_clinic_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id) ON UPDATE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,

  addDentist: `CREATE TABLE IF NOT EXISTS dentist (
    dentist_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    clinic_id BIGINT UNSIGNED NOT NULL,
    keycloak_id CHAR(36) DEFAULT NULL,
    username VARCHAR(50) DEFAULT NULL,
    password VARBINARY(255) DEFAULT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    gender ENUM('M','F','TG') DEFAULT 'M',
    date_of_birth DATE DEFAULT NULL,
    email VARCHAR(255) DEFAULT NULL,
    phone_number VARCHAR(15) NOT NULL,
    alternate_phone_number VARCHAR(15) DEFAULT NULL,
    specialisation VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
    designation VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
    member_of LONGTEXT DEFAULT NULL,
    experience_years INT NOT NULL,
    license_number VARCHAR(20) NOT NULL,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    country VARCHAR(50) NOT NULL,
    pin_code VARCHAR(10) NOT NULL,
    profile_picture VARCHAR(255) DEFAULT NULL,
    working_hours LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(working_hours)),
    available_days LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(available_days)),
    consultation_fee DECIMAL(12,2) DEFAULT 0.00,
    currency_code VARCHAR(10) DEFAULT NULL,
    min_booking_fee DECIMAL(12,2) DEFAULT 0.00,
    ratings DECIMAL(3,2) DEFAULT 0.00,
    reviews_count INT DEFAULT 0,
    appointment_count INT DEFAULT 0,
    bio LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(bio)),
    teleconsultation_supported TINYINT(1) NOT NULL DEFAULT 0,
    languages_spoken LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(languages_spoken)),
    social_links LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
    internship LONGTEXT DEFAULT NULL,
    position_held LONGTEXT DEFAULT NULL,
    research_projects LONGTEXT DEFAULT NULL,
    publication LONGTEXT DEFAULT NULL,
    social_activities LONGTEXT DEFAULT NULL,
    last_login TIMESTAMP NULL DEFAULT NULL,
    duration INT DEFAULT NULL,
    status TINYINT(1) DEFAULT 1,
    created_by VARCHAR(30) NOT NULL,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_by VARCHAR(30) DEFAULT NULL,
    updated_time TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (dentist_id),
    KEY idx_dentist_keycloak_id (keycloak_id),
    KEY idx_tenant_id (tenant_id),
    KEY idx_phone_number (phone_number),
    KEY idx_clinic_id (clinic_id),
    CONSTRAINT fk_dentist_clinic FOREIGN KEY (clinic_id) REFERENCES clinic (clinic_id) ON UPDATE CASCADE,
    CONSTRAINT fk_dentist_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id) ON UPDATE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,

  addPatient: `CREATE TABLE IF NOT EXISTS patient (
    patient_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    keycloak_id CHAR(36) DEFAULT NULL,
    username VARCHAR(50) DEFAULT NULL,
    password VARBINARY(255) DEFAULT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(255) DEFAULT NULL,
    phone_number VARCHAR(15) NOT NULL,
    alternate_phone_number VARCHAR(15) DEFAULT NULL,
    profile_picture VARCHAR(255) DEFAULT NULL,
    date_of_birth DATE NOT NULL,
    gender ENUM('M','F','TG') NOT NULL DEFAULT 'M',
    blood_group VARCHAR(10) DEFAULT NULL,
    address TEXT NOT NULL,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    country VARCHAR(50) NOT NULL,
    pin_code VARCHAR(10) NOT NULL,
    pre_history TEXT DEFAULT NULL,
    current_medications TEXT DEFAULT NULL,
    dentist_preference BIGINT UNSIGNED DEFAULT NULL,
    smoking_status VARCHAR(100) NOT NULL,
    alcohol_consumption VARCHAR(100) NOT NULL,
    emergency_contact_name VARCHAR(255) NOT NULL,
    emergency_contact_number VARCHAR(15) NOT NULL,
    insurance_provider VARCHAR(255) DEFAULT NULL,
    insurance_policy_number VARCHAR(10) DEFAULT NULL,
    insurance_policy_start_date DATE DEFAULT NULL,
    insurance_policy_end_date DATE DEFAULT NULL,
    treatment_history LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(treatment_history)),
    appointment_count INT DEFAULT NULL,
    first_visit_date TIMESTAMP NULL DEFAULT NULL,
    last_appointment_date DATETIME NULL DEFAULT NULL,
    referred_by VARCHAR(100) DEFAULT NULL,
    profession VARCHAR(100) DEFAULT NULL,
    tooth_details TEXT DEFAULT NULL,
    created_by VARCHAR(30) NOT NULL,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_by VARCHAR(30) DEFAULT NULL,
    updated_time TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (patient_id),
    KEY idx_patient_keycloak_id (keycloak_id),
    KEY fk_patient_tenant (tenant_id),
    KEY fk_patient_dentist (dentist_preference),
    CONSTRAINT fk_patient_dentist FOREIGN KEY (dentist_preference) REFERENCES dentist (dentist_id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_patient_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id) ON UPDATE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;`,

  addPrescription: `CREATE TABLE IF NOT EXISTS prescription (
    prescription_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    clinic_id BIGINT UNSIGNED NOT NULL,
    patient_id BIGINT UNSIGNED NOT NULL,
    dentist_id BIGINT UNSIGNED NOT NULL,
    treatment_id BIGINT UNSIGNED NOT NULL,
    medication TEXT DEFAULT NULL,
    generic_name VARCHAR(255) DEFAULT NULL,
    brand_name VARCHAR(255) DEFAULT NULL,
    dosage INT DEFAULT 0,
    frequency VARCHAR(50) DEFAULT NULL,
    quantity INT DEFAULT 0,
    refill_allowed TINYINT(1) DEFAULT 0,
    refill_count INT DEFAULT 0,
    side_effects TEXT DEFAULT NULL,
    start_date DATE DEFAULT NULL,
    end_date DATE DEFAULT NULL,
    instructions TEXT DEFAULT NULL,
    notes TEXT DEFAULT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_by VARCHAR(30) NOT NULL,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_by VARCHAR(30) DEFAULT NULL,
    updated_time TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (prescription_id),
    KEY fk_prescription_patient (patient_id),
    KEY fk_prescription_dentist (dentist_id),
    KEY fk_prescription_treatment (treatment_id),
    KEY fk_prescription_tenant (tenant_id),
    KEY fk_prescription_clinic (clinic_id),
    CONSTRAINT fk_prescription_clinic FOREIGN KEY (clinic_id) REFERENCES clinic (clinic_id) ON UPDATE CASCADE,
    CONSTRAINT fk_prescription_dentist FOREIGN KEY (dentist_id) REFERENCES dentist (dentist_id) ON UPDATE CASCADE,
    CONSTRAINT fk_prescription_patient FOREIGN KEY (patient_id) REFERENCES patient (patient_id) ON UPDATE CASCADE,
    CONSTRAINT fk_prescription_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id) ON UPDATE CASCADE,
    CONSTRAINT fk_prescription_treatment FOREIGN KEY (treatment_id) REFERENCES treatment (treatment_id) ON UPDATE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;`,

  addStatusType: `CREATE TABLE IF NOT EXISTS statustype (
    status_type_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    status_type VARCHAR(100) NOT NULL,
    created_by VARCHAR(30) NOT NULL,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_by VARCHAR(30) DEFAULT NULL,
    updated_time TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (status_type_id),
    UNIQUE KEY uk_status_type (status_type)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;`,

  addStatusTypeSub: `CREATE TABLE IF NOT EXISTS statustypesub (
    status_type_sub_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    status_type_id BIGINT UNSIGNED NOT NULL,
    status_type_sub VARCHAR(100) NOT NULL,
    status_type_sub_ref VARCHAR(100) NOT NULL,
    created_by VARCHAR(30) NOT NULL,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_by VARCHAR(30) DEFAULT NULL,
    updated_time TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (status_type_sub_id),
    KEY idx_status_type_id (status_type_id),
    CONSTRAINT fk_statustypesub_status_type FOREIGN KEY (status_type_id) REFERENCES statustype (status_type_id) ON UPDATE CASCADE,
    CONSTRAINT fk_statustypesub_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id) ON UPDATE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;`,

  addTenant: `CREATE TABLE IF NOT EXISTS tenant (
    tenant_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_name VARCHAR(50) NOT NULL,
    tenant_domain VARCHAR(255) NOT NULL,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    created_by VARCHAR(30) NOT NULL DEFAULT 'ADMIN',
    updated_time TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(),
    updated_by VARCHAR(30) DEFAULT NULL,
    tenant_app_name VARCHAR(100) DEFAULT NULL,
    tenant_app_logo VARCHAR(255) DEFAULT NULL,
    tenant_app_font VARCHAR(50) DEFAULT NULL,
    tenant_app_themes VARCHAR(50) DEFAULT NULL,
    PRIMARY KEY (tenant_id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;`,

  addTreatment: `CREATE TABLE IF NOT EXISTS treatment (
    treatment_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    appointment_id BIGINT UNSIGNED NOT NULL,
    patient_id BIGINT UNSIGNED NOT NULL,
    dentist_id BIGINT UNSIGNED NOT NULL,
    clinic_id BIGINT UNSIGNED NOT NULL,
    diagnosis TEXT DEFAULT NULL,
    treatment_procedure TEXT DEFAULT NULL,
    treatment_type VARCHAR(100) NOT NULL,
    treatment_status VARCHAR(100) NOT NULL,
    treatment_date DATE NOT NULL,
    cost DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    duration VARCHAR(50) NOT NULL,
    teeth_involved VARCHAR(255) NOT NULL,
    complications TEXT DEFAULT NULL,
    follow_up_required TINYINT(1) NOT NULL DEFAULT 0,
    follow_up_date DATE DEFAULT NULL,
    follow_up_notes TEXT DEFAULT NULL,
    anesthesia_used TINYINT(1) NOT NULL DEFAULT 0,
    anesthesia_type VARCHAR(100) DEFAULT NULL,
    technician_assisted VARCHAR(255) DEFAULT NULL,
    notes TEXT DEFAULT NULL,
    created_by VARCHAR(30) NOT NULL,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_by VARCHAR(30) DEFAULT NULL,
    updated_time TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (treatment_id),
    KEY fk_treatment_appointment (appointment_id),
    KEY fk_treatment_patient (patient_id),
    KEY fk_treatment_dentist (dentist_id),
    KEY fk_treatment_clinic (clinic_id),
    KEY fk_treatment_tenant (tenant_id),
    CONSTRAINT fk_treatment_appointment FOREIGN KEY (appointment_id) REFERENCES appointment (appointment_id) ON UPDATE CASCADE,
    CONSTRAINT fk_treatment_clinic FOREIGN KEY (clinic_id) REFERENCES clinic (clinic_id) ON UPDATE CASCADE,
    CONSTRAINT fk_treatment_dentist FOREIGN KEY (dentist_id) REFERENCES dentist (dentist_id) ON UPDATE CASCADE,
    CONSTRAINT fk_treatment_patient FOREIGN KEY (patient_id) REFERENCES patient (patient_id) ON UPDATE CASCADE,
    CONSTRAINT fk_treatment_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id) ON UPDATE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;`,

  addExpense: `CREATE TABLE IF NOT EXISTS expense (
    expense_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    clinic_id BIGINT UNSIGNED NOT NULL,
    expense_amount DECIMAL(12,2) DEFAULT 0.00,
    expense_category VARCHAR(255) DEFAULT NULL,
    expense_reason VARCHAR(255) DEFAULT NULL,
    expense_date DATE DEFAULT NULL,
    mode_of_payment VARCHAR(100) DEFAULT NULL,
    receipt_number VARCHAR(100) DEFAULT NULL,
    paid_by VARCHAR(100) DEFAULT NULL,
    paid_by_user VARCHAR(100) DEFAULT NULL,
    paid_to VARCHAR(100) DEFAULT NULL,
    created_by VARCHAR(30) NOT NULL,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_by VARCHAR(30) DEFAULT NULL,
    updated_time TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (expense_id),
    KEY fk_expense_clinic (clinic_id),
    KEY fk_expense_tenant (tenant_id),
    CONSTRAINT fk_expense_clinic FOREIGN KEY (clinic_id) REFERENCES clinic (clinic_id) ON UPDATE CASCADE,
    CONSTRAINT fk_expense_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id) ON UPDATE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;`,

  addSupplier: `CREATE TABLE IF NOT EXISTS supplier (
    supplier_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    supplier_code VARCHAR(50) DEFAULT NULL,
    tenant_id BIGINT UNSIGNED NOT NULL,
    clinic_id BIGINT UNSIGNED NOT NULL,
    keycloak_id CHAR(36) DEFAULT NULL,
    username VARCHAR(50) DEFAULT NULL,
    password VARBINARY(255) DEFAULT NULL,
    name VARCHAR(100) DEFAULT NULL,
    category VARCHAR(100) DEFAULT NULL,
    status TINYINT(1) DEFAULT 1,
    email VARCHAR(150) DEFAULT NULL,
    phone_number VARCHAR(15) NOT NULL,
    alternate_phone_number VARCHAR(15) NULL,
    logo_url VARCHAR(255) DEFAULT NULL,
    fax VARCHAR(50) DEFAULT NULL,
    website VARCHAR(255) DEFAULT NULL,
    gst_number VARCHAR(50) DEFAULT NULL,
    tax_id VARCHAR(50) DEFAULT NULL,
    pan_number VARCHAR(50) DEFAULT NULL,
    mode_of_payment VARCHAR(100) DEFAULT NULL,
    preferred_currency VARCHAR(10) DEFAULT NULL,
    credit_limit DECIMAL(12,2) DEFAULT NULL,
    opening_balance DECIMAL(12,2) DEFAULT NULL,
    notes TEXT DEFAULT NULL,
    address_type ENUM('billing','shipping','office') DEFAULT 'billing',
    address VARCHAR(100) DEFAULT NULL,
    city VARCHAR(100) DEFAULT NULL,
    state VARCHAR(100) DEFAULT NULL,
    postal_code VARCHAR(10) DEFAULT NULL,
    country VARCHAR(100) DEFAULT NULL,
    created_by VARCHAR(30) NOT NULL,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_by VARCHAR(30) DEFAULT NULL,
    updated_time TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (supplier_id),
    UNIQUE KEY uq_supplier_code (supplier_code),
    KEY idx_supplier_keycloak_id (keycloak_id),
    KEY fk_supplier_clinic (clinic_id),
    KEY fk_supplier_tenant (tenant_id),
    CONSTRAINT fk_supplier_clinic FOREIGN KEY (clinic_id) REFERENCES clinic (clinic_id) ON UPDATE CASCADE,
    CONSTRAINT fk_supplier_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id) ON UPDATE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;`,

  addSupplierProducts: `CREATE TABLE IF NOT EXISTS supplier_products (
    supplier_product_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    clinic_id BIGINT UNSIGNED NOT NULL,
    supplier_id BIGINT UNSIGNED NOT NULL,
    product_name VARCHAR(255) DEFAULT NULL,
    description TEXT DEFAULT NULL,
    image_url VARCHAR(255) DEFAULT NULL,
    unit_price DECIMAL(12,2) DEFAULT NULL,
    unit VARCHAR(50) DEFAULT NULL,
    moq INT DEFAULT NULL,
    lead_time_days INT DEFAULT NULL,
    currency VARCHAR(10) DEFAULT NULL,
    active TINYINT(1) DEFAULT 1,
    created_by VARCHAR(30) NOT NULL,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_by VARCHAR(30) DEFAULT NULL,
    updated_time TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (supplier_product_id),
    KEY fk_supplier_product_supplier (supplier_id),
    KEY fk_supplier_product_tenant (tenant_id),
    KEY fk_supplier_product_clinic (clinic_id),
    CONSTRAINT fk_supplier_product_supplier FOREIGN KEY (supplier_id) REFERENCES supplier (supplier_id) ON UPDATE CASCADE,
    CONSTRAINT fk_supplier_product_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id) ON UPDATE CASCADE,
    CONSTRAINT fk_supplier_product_clinic FOREIGN KEY (clinic_id) REFERENCES clinic (clinic_id) ON UPDATE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;`,

  addPurchaseOrder: `CREATE TABLE IF NOT EXISTS purchase_orders (
    purchase_order_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    clinic_id BIGINT UNSIGNED NOT NULL,
    dentist_id BIGINT UNSIGNED DEFAULT NULL,
    supplier_id BIGINT UNSIGNED NOT NULL,
    supplier_product_id BIGINT UNSIGNED NOT NULL,
    order_number VARCHAR(100) DEFAULT NULL,
    order_date DATE DEFAULT NULL,
    product_name VARCHAR(100) DEFAULT NULL,
    quantity INT DEFAULT NULL,
    total_amount DECIMAL(12,2) DEFAULT NULL,
    status ENUM('pending','confirmed','shipped','delivered','cancelled') DEFAULT 'pending',
    delivery_date DATE DEFAULT NULL,
    created_by VARCHAR(30) NOT NULL,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_by VARCHAR(30) DEFAULT NULL,
    updated_time TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (purchase_order_id),
    KEY fk_purchase_order_supplier (supplier_id),
    KEY fk_purchase_order_supplier_product (supplier_product_id),
    KEY fk_purchase_order_tenant (tenant_id),
    KEY fk_purchase_order_clinic (clinic_id),
    KEY fk_purchase_order_dentist (dentist_id),
    CONSTRAINT fk_po_supplier FOREIGN KEY (supplier_id) REFERENCES supplier (supplier_id) ON UPDATE CASCADE,
    CONSTRAINT fk_po_supplier_product FOREIGN KEY (supplier_product_id) REFERENCES supplier_products (supplier_product_id) ON UPDATE CASCADE,
    CONSTRAINT fk_po_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id) ON UPDATE CASCADE,
    CONSTRAINT fk_po_clinic FOREIGN KEY (clinic_id) REFERENCES clinic (clinic_id) ON UPDATE CASCADE,
    CONSTRAINT fk_po_dentist FOREIGN KEY (dentist_id) REFERENCES dentist (dentist_id) ON UPDATE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;`,

  addSupplierPayments: `CREATE TABLE IF NOT EXISTS supplier_payments (
    supplier_payment_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    clinic_id BIGINT UNSIGNED NOT NULL,
    supplier_id BIGINT UNSIGNED NOT NULL,
    purchase_order_id BIGINT UNSIGNED NOT NULL,
    amount DECIMAL(12,2) NOT NULL,
    paid_amount DECIMAL(12,2) DEFAULT 0.00,
    balance_amount DECIMAL(12,2) DEFAULT 0.00,
    supplier_payment_documents TEXT DEFAULT NULL,
    mode_of_payment VARCHAR(50) DEFAULT NULL,
    receipt_number VARCHAR(100) DEFAULT NULL,
    bank_name VARCHAR(100) DEFAULT NULL,
    bank_account_number VARCHAR(100) DEFAULT NULL,
    bank_ifsc VARCHAR(20) DEFAULT NULL,
    transaction_id VARCHAR(100) DEFAULT NULL,
    payment_date DATE DEFAULT NULL,
    created_by VARCHAR(30) NOT NULL,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_by VARCHAR(30) DEFAULT NULL,
    updated_time TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(),
    supplier_payment_type ENUM('SP','FP') DEFAULT 'SP',
    PRIMARY KEY (supplier_payment_id),
    KEY fk_sp_supplier (supplier_id),
    KEY fk_sp_purchase_order (purchase_order_id),
    KEY fk_sp_tenant (tenant_id),
    KEY fk_sp_clinic (clinic_id),
    CONSTRAINT fk_sp_supplier FOREIGN KEY (supplier_id) REFERENCES supplier (supplier_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_sp_purchase_order FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders (purchase_order_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_sp_clinic FOREIGN KEY (clinic_id) REFERENCES clinic (clinic_id) ON UPDATE CASCADE,
    CONSTRAINT fk_sp_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id) ON UPDATE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;`,

  addSupplierReview: `CREATE TABLE IF NOT EXISTS supplier_reviews (
    supplier_review_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    clinic_id BIGINT UNSIGNED NOT NULL,
    supplier_id BIGINT UNSIGNED NOT NULL,
    purchase_order_id BIGINT UNSIGNED NOT NULL,
    rating_quality INT CHECK (rating_quality BETWEEN 1 AND 5),
    rating_delivery INT CHECK (rating_delivery BETWEEN 1 AND 5),
    rating_communication INT CHECK (rating_communication BETWEEN 1 AND 5),
    comment TEXT DEFAULT NULL,
    reviewed_by VARCHAR(30) NOT NULL,
    created_by VARCHAR(30) NOT NULL,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_by VARCHAR(30) DEFAULT NULL,
    updated_time TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (supplier_review_id),
    KEY fk_supplier_review_supplier (supplier_id),
    KEY fk_supplier_review_tenant (tenant_id),
    KEY fk_supplier_review_clinic (clinic_id),
    KEY fk_supplier_review_purchase_order (purchase_order_id),
    CONSTRAINT fk_supplier_review_supplier FOREIGN KEY (supplier_id) REFERENCES supplier (supplier_id) ON UPDATE CASCADE,
    CONSTRAINT fk_supplier_review_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id) ON UPDATE CASCADE,
    CONSTRAINT fk_supplier_review_clinic FOREIGN KEY (clinic_id) REFERENCES clinic (clinic_id) ON UPDATE CASCADE,
    CONSTRAINT fk_supplier_review_purchase_order FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders (purchase_order_id) ON UPDATE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;`,

  addReminder: `CREATE TABLE IF NOT EXISTS reminder (
    reminder_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    clinic_id BIGINT UNSIGNED NOT NULL,
    dentist_id BIGINT UNSIGNED DEFAULT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT DEFAULT NULL,
    reminder_repeat ENUM('daily','weekly','monthly','yearly') DEFAULT NULL,
    category VARCHAR(100) DEFAULT NULL,
    reminder_type VARCHAR(100) DEFAULT NULL,
    type ENUM('reminder','todo') NOT NULL,
    is_recurring TINYINT(1) DEFAULT NULL,
    start_date DATE NOT NULL,
    time TIME NOT NULL,
    repeat_interval INT NOT NULL DEFAULT 1,
    repeat_count INT NOT NULL DEFAULT 0,
    repeat_weekdays VARCHAR(20) DEFAULT NULL,
    monthly_week TEXT DEFAULT NULL,
    monthly_weekdays TEXT DEFAULT NULL,
    repeat_end_date DATE DEFAULT NULL,
    monthly_option VARCHAR(20) DEFAULT NULL,
    notify TINYINT(1) DEFAULT 0,
    notify_before_hours INT DEFAULT NULL,
    reminder_reason VARCHAR(255) DEFAULT NULL,
    status VARCHAR(20) DEFAULT NULL,
    created_by VARCHAR(30) NOT NULL,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_by VARCHAR(30) DEFAULT NULL,
    updated_time TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (reminder_id),
    KEY fk_reminder_clinic (clinic_id),
    KEY fk_reminder_tenant (tenant_id),
    CONSTRAINT fk_reminder_clinic FOREIGN KEY (clinic_id) REFERENCES clinic (clinic_id) ON UPDATE CASCADE,
    CONSTRAINT fk_reminder_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id) ON UPDATE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;`,

  addAppointmentReschedules: `CREATE TABLE IF NOT EXISTS appointment_reschedules (
    rescheduled_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    clinic_id BIGINT UNSIGNED NOT NULL,
    dentist_id BIGINT UNSIGNED NOT NULL,
    original_appointment_id BIGINT UNSIGNED NOT NULL,
    new_appointment_id BIGINT UNSIGNED NOT NULL,
    previous_date DATE NOT NULL,
    previous_time TIME NOT NULL,
    new_date DATE NOT NULL,
    new_start_time TIME NOT NULL,
    new_end_time TIME NOT NULL,
    reason TEXT NOT NULL,
    charge_applicable TINYINT(1) NOT NULL DEFAULT 0,
    charge_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    rescheduled_by VARCHAR(30) NOT NULL,
    rescheduled_at TIMESTAMP NULL DEFAULT NULL,
    created_by VARCHAR(30) NOT NULL,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_by VARCHAR(30) DEFAULT NULL,
    updated_time TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (rescheduled_id),
    KEY fk_appointment_reschedules_clinic (clinic_id),
    KEY fk_appointment_reschedules_tenant (tenant_id),
    KEY fk_appointment_reschedules_dentist (dentist_id),
    CONSTRAINT fk_appointment_reschedules_clinic FOREIGN KEY (clinic_id) REFERENCES clinic (clinic_id) ON UPDATE CASCADE,
    CONSTRAINT fk_appointment_reschedules_dentist FOREIGN KEY (dentist_id) REFERENCES dentist (dentist_id) ON UPDATE CASCADE,
    CONSTRAINT fk_appointment_reschedules_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id) ON UPDATE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;`,

  addPayment: `CREATE TABLE IF NOT EXISTS payment (
    payment_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    clinic_id BIGINT UNSIGNED NOT NULL,
    patient_id BIGINT UNSIGNED NOT NULL,
    dentist_id BIGINT UNSIGNED NOT NULL,
    appointment_id BIGINT UNSIGNED NOT NULL,
    amount DECIMAL(12,2) NULL DEFAULT 0.00,
    discount_applied DECIMAL(12,2) DEFAULT 0.00,
    total_amount DECIMAL(12,2) DEFAULT 0.00,
    payment_for ENUM('booking','treatment','late') NULL,
    final_amount DECIMAL(12,2) NULL DEFAULT 0.00,
    mode_of_payment VARCHAR(100) NULL,
    payment_source VARCHAR(100) NULL,
    payment_reference TEXT DEFAULT NULL,
    payment_status VARCHAR(100) NULL,
    payment_verified TINYINT(1) DEFAULT 0,
    receipt_number VARCHAR(25) DEFAULT NULL,
    insurance_number VARCHAR(25) DEFAULT NULL,
    payment_date DATETIME DEFAULT NULL,
    created_by VARCHAR(30) NOT NULL,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_by VARCHAR(30) DEFAULT NULL,
    updated_time TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (payment_id),
    KEY fk_payment_tenant (tenant_id),
    KEY fk_payment_clinic (clinic_id),
    KEY fk_payment_patient (patient_id),
    KEY fk_payment_dentist (dentist_id),
    KEY fk_payment_appointment (appointment_id),
    CONSTRAINT fk_payment_appointment FOREIGN KEY (appointment_id) REFERENCES appointment (appointment_id) ON UPDATE CASCADE,
    CONSTRAINT fk_payment_clinic FOREIGN KEY (clinic_id) REFERENCES clinic (clinic_id) ON UPDATE CASCADE,
    CONSTRAINT fk_payment_dentist FOREIGN KEY (dentist_id) REFERENCES dentist (dentist_id) ON UPDATE CASCADE,
    CONSTRAINT fk_payment_patient FOREIGN KEY (patient_id) REFERENCES patient (patient_id) ON UPDATE CASCADE,
    CONSTRAINT fk_payment_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id) ON UPDATE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;`,

  addReception: `CREATE TABLE IF NOT EXISTS reception (
    reception_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    clinic_id BIGINT UNSIGNED NOT NULL,
    keycloak_id CHAR(36) DEFAULT NULL,
    username VARCHAR(50) DEFAULT NULL,
    password VARBINARY(255) DEFAULT NULL,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) DEFAULT NULL,
    phone_number VARCHAR(15) NOT NULL,
    alternate_phone_number VARCHAR(15) DEFAULT NULL,
    profile_picture VARCHAR(255) DEFAULT NULL,
    date_of_birth DATE NOT NULL,
    gender ENUM('M','F','TG') NOT NULL DEFAULT 'M',
    status TINYINT(1) DEFAULT 1,
    address TEXT NOT NULL,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    country VARCHAR(50) NOT NULL,
    pincode VARCHAR(10) NOT NULL,
    last_login DATETIME DEFAULT NULL,
    created_by VARCHAR(30) NOT NULL,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_by VARCHAR(30) DEFAULT NULL,
    updated_time TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (reception_id),
    KEY idx_reception_keycloak_id (keycloak_id),
    KEY fk_reception_tenant (tenant_id),
    KEY fk_reception_clinic (clinic_id),
    CONSTRAINT fk_reception_clinic FOREIGN KEY (clinic_id) REFERENCES clinic (clinic_id) ON UPDATE CASCADE,
    CONSTRAINT fk_reception_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id) ON UPDATE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;`,

  addToothDetails: `CREATE TABLE IF NOT EXISTS toothdetails (
    toothdetails_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    clinic_id BIGINT UNSIGNED NOT NULL,
    dentist_id BIGINT UNSIGNED NOT NULL,
    patient_id BIGINT UNSIGNED NOT NULL,
    tooth_id TINYINT UNSIGNED NOT NULL,
    tooth_name VARCHAR(100) NOT NULL,
    tooth_position VARCHAR(100) NOT NULL,
    disease_type VARCHAR(100) NOT NULL,
    disease_name VARCHAR(100) NOT NULL,
    treatment_date DATE NOT NULL,
    description TEXT,
    created_by VARCHAR(30) NOT NULL,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_by VARCHAR(30) DEFAULT NULL,
    updated_time TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (toothdetails_id),
    KEY fk_toothdetails_dentist (dentist_id),
    KEY fk_toothdetails_patient (patient_id),
    KEY fk_toothdetails_tenant (tenant_id),
    KEY fk_toothdetails_clinic (clinic_id),
    KEY idx_toothdetails_treatment_date (treatment_date),
    CONSTRAINT fk_toothdetails_clinic FOREIGN KEY (clinic_id) REFERENCES clinic (clinic_id) ON UPDATE CASCADE,
    CONSTRAINT fk_toothdetails_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id) ON UPDATE CASCADE,
    CONSTRAINT fk_toothdetails_dentist FOREIGN KEY (dentist_id) REFERENCES dentist (dentist_id) ON UPDATE CASCADE,
    CONSTRAINT fk_toothdetails_patient FOREIGN KEY (patient_id) REFERENCES patient (patient_id) ON UPDATE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;`,

  addLoginHistory: `CREATE TABLE IF NOT EXISTS loginhistory (
    loginhistory_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED DEFAULT NULL,
    clinic_id BIGINT UNSIGNED DEFAULT NULL,
    keycloak_user_id CHAR(36) DEFAULT NULL,
    session_id VARCHAR(36) DEFAULT NULL,
    login_time DATETIME DEFAULT NULL,
    logout_time DATETIME DEFAULT NULL,
    ip_address VARCHAR(45) DEFAULT NULL,
    device_info TEXT DEFAULT NULL,
    browser_info TEXT DEFAULT NULL,
    created_time TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (loginhistory_id),
    KEY idx_loginhistory_keycloak_user_id (keycloak_user_id),
    KEY fk_login_history_clinic (clinic_id),
    KEY fk_login_history_tenant (tenant_id),
    CONSTRAINT fk_login_history_clinic FOREIGN KEY (clinic_id) REFERENCES clinic (clinic_id) ON UPDATE CASCADE,
    CONSTRAINT fk_login_history_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id) ON UPDATE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;`,

  addUserActivity: `CREATE TABLE IF NOT EXISTS useractivity (
    useractivity_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    keycloak_user_id CHAR(36) DEFAULT NULL,
    ip_address VARCHAR(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
    browser VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
    device VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
    login_time TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
    logout_time TIMESTAMP NULL DEFAULT NULL,
    duration TIME DEFAULT NULL,
    created_time TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (useractivity_id),
    KEY idx_useractivity_keycloak_user_id (keycloak_user_id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;`,

  addNotificationSend: `CREATE TABLE IF NOT EXISTS notifications (
    notification_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    clinic_id BIGINT UNSIGNED NOT NULL,
    sender_role VARCHAR(20) NOT NULL,
    sender_id BIGINT UNSIGNED NOT NULL,
    type VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    message TEXT,
    reference_id BIGINT UNSIGNED DEFAULT NULL,
    created_by VARCHAR(50),
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(50),
    updated_time TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (notification_id),
    CONSTRAINT fk_notification_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id) ON DELETE CASCADE ON UPDATE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;`,

  addNotificationRecipients: `CREATE TABLE IF NOT EXISTS notificationrecipients (
    notification_recipient_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    notification_id BIGINT UNSIGNED NOT NULL,
    receiver_role VARCHAR(20) NOT NULL,
    receiver_id BIGINT UNSIGNED NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'unread',
    created_by VARCHAR(50),
    delivered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    read_at TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (notification_recipient_id),
    CONSTRAINT fk_notification_recipients_notification FOREIGN KEY (notification_id) REFERENCES notifications (notification_id) ON DELETE CASCADE ON UPDATE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;`,

  addPatientClinic: `CREATE TABLE IF NOT EXISTS patient_clinic (
    patient_clinic_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    patient_id BIGINT UNSIGNED NOT NULL,
    clinic_id BIGINT UNSIGNED NOT NULL,
    created_by VARCHAR(50),
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(50),
    updated_time TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (patient_clinic_id),
    UNIQUE KEY uk_patient_clinic (patient_id, clinic_id),
    CONSTRAINT fk_patient_clinic_patient FOREIGN KEY (patient_id) REFERENCES patient (patient_id) ON DELETE CASCADE,
    CONSTRAINT fk_patient_clinic_clinic FOREIGN KEY (clinic_id) REFERENCES clinic (clinic_id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;`,

  addDocumentTable: `CREATE TABLE IF NOT EXISTS document (
    document_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    table_name VARCHAR(100) NOT NULL,
    table_id BIGINT UNSIGNED NOT NULL,
    field_name VARCHAR(100) NOT NULL,
    file_url VARCHAR(255) NOT NULL,
    description VARCHAR(255) NULL,
    created_by VARCHAR(30) NOT NULL,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_by VARCHAR(30) DEFAULT NULL,
    updated_time TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (document_id),
    KEY idx_table_reference (table_name, table_id, field_name)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;`
};

module.exports = { createTableQuery };