const dentistQuery = {
  createDentistTable: `
  CREATE TABLE IF NOT EXISTS dentist (
  dentist_id int(11) NOT NULL AUTO_INCREMENT,
  tenant_id int(6) NOT NULL,
  clinic_id int(11) DEFAULT NULL,
  first_name varchar(50) NOT NULL,
  last_name varchar(50) NOT NULL,
  gender enum('M','F','TG') DEFAULT 'M',
  date_of_birth date DEFAULT NULL,
  email varchar(255) DEFAULT NULL,
  phone_number varchar(15) NOT NULL,
  alternate_phone_number varchar(15) DEFAULT NULL,
  specialization longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(specialization)),
  qualifications longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(qualifications)),
  experience_years int(2) NOT NULL,
  license_number varchar(20) NOT NULL,
  clinic_name varchar(150) DEFAULT NULL,
  clinic_address varchar(300) DEFAULT NULL,
  city varchar(100) NOT NULL,
  state varchar(100) NOT NULL,
  country varchar(50) NOT NULL,
  pin_code varchar(6) NOT NULL,
  working_hours longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(working_hours)),
  available_days longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(available_days)),
  consultation_fee decimal(10,2) DEFAULT NULL,
  ratings decimal(3,2) DEFAULT NULL,
  reviews_count int(11) DEFAULT NULL,
  appointment_count int(11) DEFAULT NULL,
  profile_picture varchar(255) DEFAULT NULL,
  bio longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(bio)),
  teleconsultation_supported tinyint(1) NOT NULL DEFAULT 0,
  insurance_supported tinyint(1) NOT NULL DEFAULT 0,
  languages_spoken longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(languages_spoken)),
  awards_certifications varchar(255) DEFAULT NULL,
  social_links longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(social_links)),
  last_login timestamp NULL DEFAULT NULL,
  created_by varchar(30) NOT NULL,
  created_time timestamp NOT NULL DEFAULT current_timestamp(),
  updated_by varchar(30) DEFAULT NULL,
  updated_time timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (dentist_id),
  KEY idx_tenant_id (tenant_id),
  KEY idx_phone_number (phone_number),
  KEY clinic_id (clinic_id),
  CONSTRAINT fk_dentist_clinic FOREIGN KEY (clinic_id) REFERENCES clinic (clinic_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_dentist_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


      `,
  addDentist: `INSERT INTO dentist (
      tenant_id,
      first_name,
      last_name,
      gender,
      dob,
      email,
      phone_number,
      alternate_phone_number,
      specialization,
      experience_years,
      license_number,
      qualifications,
      clinic_name,
      clinic_address,
      city,
      state,
      country,
      pin_code,
      working_hours,
      available_days,
      consultation_fee,
      ratings,
      reviews_count,
      appointment_count,
      profile_picture,
      bio,
      teleconsultation_supported,
      insurance_supported,
      languages_spoken,
      awards_certifications,
      social_links,
      last_login,
      created_by
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?,?,?);`,

  getAllDentistsByTenantId: `SELECT
      dentist_id,
      tenant_id,
      first_name,
      last_name,
      gender,
      dob,
      email,
      phone_number,
      alternate_phone_number,
      specialization,
      experience_years,
      license_number,
      qualifications,
      clinic_name,
      clinic_address,
      city,
      state,
      country,
      pin_code,
      working_hours,
      available_days,
      consultation_fee,
      ratings,
      reviews_count,
      appointment_count,
      profile_picture,
      bio,
      teleconsultation_supported,
      insurance_supported,
      languages_spoken,
      awards_certifications,
      social_links,
      last_login,
      created_by,
      created_time,
      updated_by,
      updated_time
    FROM dentist
    WHERE tenant_id = ? LIMIT ? OFFSET ?`,

  getDentistByTenantIdAndDentistId: `SELECT * FROM dentist WHERE tenant_id = ? AND dentist_id = ?;`,

  checkDentistExistsByTenantIdAndDentistId: `SELECT 1 FROM dentist WHERE tenant_id = ? AND dentist_id = ?;`,

  updateDentist: `UPDATE dentist SET
      tenant_id = ?,
      first_name = ?,
      last_name = ?,
      gender = ?,
      dob = ?,
      email = ?,
      phone_number = ?,
      alternate_phone_number = ?,
      specialization = ?,
      experience_years = ?,
      license_number = ?,
      qualifications = ?,
      clinic_name = ?,
      clinic_address = ?,
      city = ?,
      state = ?,
      country = ?,
      pin_code = ?,
      working_hours = ?,
      available_days = ?,
      consultation_fee = ?,
      ratings = ?,
      reviews_count = ?,
      appointment_count = ?,
      profile_picture = ?,
      bio = ?,
      teleconsultation_supported = ?,
      insurance_supported = ?,
      languages_spoken = ?,
      awards_certifications = ?,
      social_links = ?,
      last_login = ?,
      updated_by = ?,
      updated_time = CURRENT_TIMESTAMP
    WHERE tenant_id = ? AND dentist_id = ?;`,

  deleteDentistByTenantIdAndDentistId: `DELETE FROM dentist WHERE tenant_id = ? AND dentist_id = ?;`,
};

module.exports = { dentistQuery };
