const prescriptionQuery = {
  createTable: `CREATE TABLE IF NOT EXISTS prescription (
  prescription_id INT(11) NOT NULL AUTO_INCREMENT,
  tenant_id INT(11) NOT NULL,
  clinic_id INT(11) NOT NULL,
  patient_id INT(11) NOT NULL,
  dentist_id INT(11) NOT NULL,
  treatment_id INT(11) NOT NULL,
  medication TEXT DEFAULT NULL,
  generic_name VARCHAR(255) DEFAULT NULL,
  brand_name VARCHAR(255) DEFAULT NULL,
  dosage TEXT DEFAULT NULL,
  frequency VARCHAR(50) DEFAULT NULL,
  quantity INT(11) DEFAULT NULL,
  refill_allowed TINYINT(1) DEFAULT 0,
  refill_count INT(11) DEFAULT 0,
  side_effects TEXT DEFAULT NULL,
  start_date DATE DEFAULT NULL,
  end_date DATE DEFAULT NULL,
  instructions TEXT DEFAULT NULL,
  notes TEXT DEFAULT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_by VARCHAR(20) NOT NULL,
  created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(20) DEFAULT NULL,
  updated_time TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (prescription_id),
  KEY fk_prescription_patient (patient_id),
  KEY fk_prescription_dentist (dentist_id),
  KEY fk_prescription_treatment (treatment_id),
  KEY fk_prescription_tenant (tenant_id),
  KEY fk_prescription_clinic (clinic_id),
  CONSTRAINT fk_prescription_clinic FOREIGN KEY (clinic_id) REFERENCES clinic (clinic_id),
  CONSTRAINT fk_prescription_dentist FOREIGN KEY (dentist_id) REFERENCES dentist (dentist_id),
  CONSTRAINT fk_prescription_patient FOREIGN KEY (patient_id) REFERENCES patient (patient_id),
  CONSTRAINT fk_prescription_treatment FOREIGN KEY (treatment_id) REFERENCES treatment (treatment_id),
  CONSTRAINT fk_prescription_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
`,
};

module.exports = { prescriptionQuery };
